;(function(window,document,undefined){var w,aa=aa||{};function ba(a,c,b){return a.call.apply(a.bind,arguments)}function ca(a,c,b){if(!a)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var b=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(b,e);return a.apply(c,b)}}return function(){return a.apply(c,arguments)}}function da(a,c,b){da=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ba:ca;return da.apply(null,arguments)}
var ea=aa.Ya&&Date.now||function(){return+new Date};mti={bind:function(a,c,b){var e=2<arguments.length?Array.prototype.slice.call(arguments,2):[];return function(){e.push.apply(e,arguments);return c.apply(a,e)}}};var fa={};function ga(a,c){this.g=c||a;this.A=this.g.document;this.b=void 0}w=ga.prototype;w.createElement=function(a,c,b){a=this.A.createElement(a);if(c)for(var e in c)c.hasOwnProperty(e)&&("style"==e?ha(this,a,c[e]):a.setAttribute(e,c[e]));b&&a.appendChild(this.A.createTextNode(b));return a};function C(a,c,b){a=a.A.getElementsByTagName(c)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(b,a.lastChild)}w.Aa=function(a){function c(){b.A.body?a():setTimeout(c,0)}var b=this;c()};
function ia(a){a.parentNode&&a.parentNode.removeChild(a)}function E(a,c){if(!("undefined"!==typeof SVGElement&&a instanceof SVGElement)){for(var b=a.className.split(/\s+/),e=0,d=b.length;e<d;e++)if(b[e]==c)return;b.push(c);a.className=b.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}}
function ja(a,c){if(!("undefined"!==typeof SVGElement&&a instanceof SVGElement)){for(var b=a.className.split(/\s+/),e=[],d=0,f=b.length;d<f;d++)b[d]!=c&&e.push(b[d]);a.className=e.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}}function ma(a,c){if("undefined"!==typeof SVGElement&&a instanceof SVGElement)return!1;for(var b=a.className.split(/\s+/),e=0,d=b.length;e<d;e++)if(b[e]==c)return!0;return!1}
function ha(a,c,b){if(void 0===a.b){var e=a.A.createElement("p");e.innerHTML='<a style="top:1px;">w</a>';a.b=/top/.test(e.getElementsByTagName("a")[0].getAttribute("style"))}a.b?c.setAttribute("style",b):c.style.cssText=b}
w.getComputedStyle=function(a){if("undefined"!=typeof a&&null!=a){if(1!=a.nodeType)return"";var c={};if("undefined"!=typeof a.currentStyle&&null!=a.currentStyle)return c.fontFamily=a.currentStyle.fontFamily,c.fontWeight="normal"==a.currentStyle.fontWeight?400:"bold"==a.currentStyle.fontWeight?700:a.currentStyle.fontWeight,c.fontStyle=a.currentStyle.fontStyle,c;a=this.A.defaultView.getComputedStyle(a,null);if("undefined"!=typeof a&&null!=a)return c.fontFamily=a.getPropertyValue("font-family"),c.fontWeight=
"normal"==a.getPropertyValue("font-weight")?400:"bold"==a.getPropertyValue("font-weight")?700:a.getPropertyValue("font-weight"),c.fontStyle=a.getPropertyValue("font-style"),c}return""};w.D=function(a){if("undefined"!=typeof a&&null!=a){if("undefined"!=typeof a.currentStyle)return a.currentStyle.fontFamily;if(a=this.A.defaultView.getComputedStyle(a,null))return a.getPropertyValue("font-family")}return""};
function na(a,c){var b="";if(void 0!=typeof c&&null!=c){void 0!=c&&null!=c&&"INPUT"==c.tagName&&(b+=c.value);c=c.childNodes||c;for(var e="img script noscript iframe object style param embed link meta head title br hr svg path".split(" "),d=0;d<c.length;d++)if(8!=c[d].nodeType&&0>a.indexOf(e,c[d].tagName?c[d].tagName.toLowerCase():"")){var f;f=(f=c[d].parentNode)?"undefined"!=typeof f.currentStyle?f.currentStyle.textTransform:(f=a.A.defaultView.getComputedStyle(f,null))?f.getPropertyValue("text-transform"):
"":void 0;if("none"!=f)f=1!=c[d].nodeType?c[d].nodeValue.replace(/(?:\r\n|\r|\n)/g," "):"",b+=f.toLowerCase()+f.toUpperCase();else{if("none"!=oa(a,c[d].parentNode)){var h=c[d].parentNode;f=oa(a,c[d].parentNode);if("undefined"!=typeof h){for(var g=h.childNodes,l=h=0;l<g.length;l++)1==g[l].nodeType&&h++;g="";switch(f){case "upper-alpha":g="ABCDEFGHIJKLMNOPQRSTUVWXYZ".substring(0,h);break;case "lower-latin":g="abcdefghijklmnopqrstuvwxyz".substring(0,h);break;case "decimal":g="1234567890".substring(0,
h);break;case "decimal-leading-zero":g="0"+"1234567890".substring(0,h);break;case "lower-roman":g="ivxlcdm";break;case "upper-roman":g="IVXLCDM";break;default:g=""}}b=b+g}b+=1!=c[d].nodeType?c[d].nodeValue.replace(/(?:\r\n|\r|\n)/g," "):""}}return b}}w.getElementById=function(a){return this.A.getElementById(a)};
function pa(a,c){if(document.getElementsByClassName)return document.getElementsByClassName(c);var b=[];qa(a.a,document.body,function(a){var d;d=a.className;var f;if(d)for(d=d.split(" "),f=0;f<d.length;f++)if(d[f]===c){b.push(a);break}});return b}
w.M=function(a,c,b){var e=[],d=this.D(a).split(","),f;a:if(f=!1,d instanceof Array)for(var h=0;h<d.length;h++)if(b instanceof Array)for(var g=0;g<b.length;g++){if(H(d[h])==H(b[g])){f=!0;break a}}else{if(H(d[h])==H(b)){f=!0;break}}else if(b instanceof Array)for(h=0;h<b.length;h++)if(d==b[h]){f=!0;break}if(f)return null;if(b instanceof Array)for(f=0;f<d.length;f++)if(H(d[f])!=c)if(-1<H(d[f]).indexOf(c))for(h=0;h<b.length;h++)""!=b[h]&&(e.push(b[h]),e.push(c));else e.push(d[f]);else if(b instanceof Array)for(h=
0;h<b.length;h++)""!=b[h]&&(e.push(b[h]),e.push(c));else e.push(b),e.push(c);else for(f=0;f<d.length;f++)H(d[f])!=c?-1<H(d[f]).indexOf(c)?(e.push(b),e.push(c)):e.push(d[f]):(e.push(b),e.push(c));e=sa(e);if(1<e.length&&e[0]!=c){b="";for(f=0;f<e.length;f++)b+="'"+e[f]+"'",f!=e.length-1&&(b+=",");b+="";a.setAttribute("data-mtiFont",c);c=""+b;a.style.setProperty?a.style.setProperty("font-family",""):a.style.setAttribute("font-family","");a.setAttribute("style",a.style.cssText+"font-family:"+c+" !important;")}else return null};
function ta(a,c){for(var b=c.parentNode;null!=b;){if(b==a)return!0;b=b.parentNode}return!1}function qa(a,c,b){b(c);for(c=c.firstChild;c;)qa(a,c,b),c=c.nextSibling}function oa(a,c){if(c){if("undefined"!=typeof c.currentStyle)return c.currentStyle["list-style-type"];var b=a.A.defaultView.getComputedStyle(c,null);return b?b.getPropertyValue("list-style-type"):""}}w.indexOf=function(a,c){if(a){if(a.indexOf)return a.indexOf(c);for(var b=0;b<a.length;b++)if(a[b]==c)return b}return-1};
function H(a){return a.replace(/^\s|\s$/g,"").replace(/'|"/g,"").replace(/,\s*/g,"|")}function sa(a){for(var c={},b=[],e=0,d=a.length;e<d;++e)c.hasOwnProperty(H(a[e]))||(b.push(H(a[e])),c[H(a[e])]=1);return b}w.D=function(a){if("undefined"!=typeof a&&null!=a){if("undefined"!=typeof a.currentStyle)return a.currentStyle.fontFamily;if(a=this.A.defaultView.getComputedStyle(a,null))return a.getPropertyValue("font-family")}return""};
function ua(a){if(a&&"string"==typeof a){var c="",b=a.length,e=null;if("from"in Array&&"Set"in window)c=Array.from(new Set(a)).join("");else for(var d=0;d<b;d++)e=a.charAt(d),-1==c.indexOf(e)&&(c+=e);return c}return""};function K(a,c){this.g=a;this.b=c};function M(a,c,b,e){this.i=null!=a?a:null;this.G=null!=c?c:null;this.b=null!=b?b:null;this.g=null!=e?e:null}var va=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/;M.prototype.toString=function(){return[this.i,this.G||"",this.b||"",this.g||""].join("")};
function N(a){a=va.exec(a);var c=null,b=null,e=null,d=null;a&&(null!==a[1]&&a[1]&&(c=parseInt(a[1],10)),null!==a[2]&&a[2]&&(b=parseInt(a[2],10)),null!==a[3]&&a[3]&&(e=parseInt(a[3],10)),null!==a[4]&&a[4]&&(/^[0-9]+$/.test(a[4])?d=parseInt(a[4],10):d=a[4]));return new M(c,b,e,d)};function O(a,c,b,e,d,f,h,g){this.P=a;this.za=c;this.Ca=b;this.Ba=e;this.ia=d;this.La=f;this.b=g}O.prototype.getName=function(){return this.P};function wa(){this.c=navigator.userAgent}var xa=new O("Unknown",new M,"Unknown",new M,"Unknown",new M,0,new K(!1,!1));
function ya(){var a=new wa;if(-1!=a.c.indexOf("MSIE")||-1!=a.c.indexOf("Trident/")){var c=za(a),b=N(Aa(a)),e=null,d=null,f=null,f=P(a.c,/Trident\/([\d\w\.]+)/,1),e=-1!=a.c.indexOf("MSIE")?N(P(a.c,/MSIE ([\d\w\.]+)/,1)):N(P(a.c,/rv:([\d\w\.]+)/,1));""!=f?(d="Trident",f=N(f)):(d="Unknown",f=new M);a=new O("MSIE",e,d,f,c,b,0,new K("Windows"==c&&6<=e.i||"Windows Phone"==c&&8<=b.i,!1))}else if(-1!=a.c.indexOf("Opera"))a:if(c="Unknown",b=N(P(a.c,/Presto\/([\d\w\.]+)/,1)),e=N(Aa(a)),null!==b.i?c="Presto":
(-1!=a.c.indexOf("Gecko")&&(c="Gecko"),b=N(P(a.c,/rv:([^\)]+)/,1))),-1!=a.c.indexOf("http://fast.fonts.net/jsapi/Opera Mini/"))d=N(P(a.c,/Opera Mini\/([\d\.]+)/,1)),a=new O("OperaMini",d,c,b,za(a),e,0,new K(!1,!1));else{if(-1!=a.c.indexOf("http://fast.fonts.net/jsapi/Version/")&&(d=N(P(a.c,/Version\/([\d\.]+)/,1)),null!==d.i)){a=new O("Opera",d,c,b,za(a),e,0,new K(10<=d.i,!1));break a}d=N(P(a.c,/Opera[\/ ]([\d\.]+)/,1));a=null!==d.i?new O("Opera",d,c,b,za(a),e,0,new K(10<=d.i,!1)):new O("Opera",new M,c,b,za(a),e,0,new K(!1,!1))}else/OPR\/[\d.]+/.test(a.c)?
a=Ba(a):/AppleWeb(K|k)it/.test(a.c)?a=Ba(a):-1!=a.c.indexOf("Gecko")?(c="Unknown",b=new M,e=N(Aa(a)),d=!1,-1!=a.c.indexOf("Firefox")?(c="Firefox",b=N(P(a.c,/Firefox\/([\d\w\.]+)/,1)),d=3<=b.i&&5<=b.G):-1!=a.c.indexOf("Mozilla")&&(c="Mozilla"),f=N(P(a.c,/rv:([^\)]+)/,1)),d||(d=1<f.i||1==f.i&&9<f.G||1==f.i&&9==f.G&&2<=f.b),a=new O(c,b,"Gecko",f,za(a),e,0,new K(d,!1))):a=xa;return a}
function za(a){var c=P(a.c,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=c)return/BB\d{2}/.test(c)&&(c="BlackBerry"),c;a=P(a.c,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS|PlayStation|CrKey)/,1);return""!=a?("Mac_PowerPC"==a?a="Macintosh":"PlayStation"==a&&(a="Linux"),a):"Unknown"}
function Aa(a){var c=P(a.c,/Windows Phone( OS)? ([^;)]+)/,2);if(c||(c=P(a.c,/(OS X|Windows NT|Android) ([^;)]+)/,2))||(c=P(a.c,/(iPhone )?OS ([\d_]+)/,2)))return c;if(c=P(a.c,/(?:Linux|CrOS|CrKey) ([^;)]+)/,1))for(var c=c.split(/\s/),b=0;b<c.length;b+=1)if(/^[\d\._]+$/.test(c[b]))return c[b];return(a=P(a.c,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function Ba(a){var c=za(a),b=N(Aa(a)),e=N(P(a.c,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,1)),d="Unknown",f=new M,f="Unknown",h=!1;/OPR\/[\d.]+/.test(a.c)?d="Opera":-1!=a.c.indexOf("Edge")?d="Edge":-1!=a.c.indexOf("Chrome")||-1!=a.c.indexOf("CrMo")||-1!=a.c.indexOf("CriOS")?d="Chrome":/Silk\/\d/.test(a.c)?d="Silk":"BlackBerry"==c||"Android"==c?d="BuiltinBrowser":-1!=a.c.indexOf("PhantomJS")?d="PhantomJS":-1!=a.c.indexOf("Safari")?d="Safari":-1!=a.c.indexOf("AdobeAIR")?d="AdobeAIR":-1!=a.c.indexOf("PlayStation")?
d="BuiltinBrowser":-1!=a.c.indexOf("FBAN")&&(d="FBWebUI");"BuiltinBrowser"==d?f="Unknown":"Silk"==d?f=P(a.c,/Silk\/([\d\._]+)/,1):"Chrome"==d?f=P(a.c,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):-1!=a.c.indexOf("http://fast.fonts.net/jsapi/Version/")?f=P(a.c,/Version\/([\d\.\w]+)/,1):"AdobeAIR"==d?f=P(a.c,/AdobeAIR\/([\d\.]+)/,1):"Opera"==d?f=P(a.c,/OPR\/([\d.]+)/,1):"PhantomJS"==d?f=P(a.c,/PhantomJS\/([\d.]+)/,1):"FBWebUI"==d?f=P(a.c,/FBSV\/([\d.]+)/,1):"Edge"==d&&(f=P(a.c,/Edge\/([\d.]+)/,1));f=N(f);h="AdobeAIR"==d?2<f.i||2==f.i&&
5<=f.G:"BlackBerry"==c?10<=b.i:"Android"==c?2<b.i||2==b.i&&1<b.G:526<=e.i||525<=e.i&&13<=e.G;return new O(d,f,"AppleWebKit",e,c,b,0,new K(h,536>e.i||536==e.i&&11>e.G))}function P(a,c,b){return(a=a.match(c))&&a[b]?a[b]:""};function Ca(a){this.g=a||"-"}Ca.prototype.b=function(a){for(var c=[],b=0;b<arguments.length;b++)c.push(arguments[b].replace(/[\W_]+/g,"").toLowerCase());return c.join(this.g)};function Da(a,c,b){this.a=a;this.g=c;this.s=b;this.b=new Ca("-")}function Ea(a){E(a.g,a.b.b("mti","loading"));Fa(a,"loading")}function Ga(a){ja(a.g,a.b.b("mti","loading"));ma(a.g,a.b.b("mti","active"))||E(a.g,a.b.b("mti","inactive"));Fa(a,"inactive")}function Fa(a,c,b){if(a.s[c])if(b)a.s[c](b.getName(),Q(b));else a.s[c]()};function R(a,c){this.P=a;this.W=4;this.T="n";var b=(c||"n4").match(/^([nio])([1-9])$/i);b&&(this.T=b[1],this.W=parseInt(b[2],10))}R.prototype.getName=function(){return this.P};R.prototype.ya=function(a){var c=[];a=a.split(/,\s*/);for(var b=0;b<a.length;b++){var e=a[b].replace(/['"]/g,"");-1==e.indexOf(" ")?c.push(e):c.push("'"+e+"'")}return c.join(",")};function Q(a){return a.T+a.W};function Ha(a,c){this.a=a;this.g=c;this.b=this.a.createElement("span",{"aria-hidden":"true"},this.g)}function Ia(a){C(a.a,"body",a.b)}function Ja(a){var c="position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+a.ya(a.P)+"!important;",b="normal",e=a.W+"00";"o"===a.T?b="oblique":"i"===a.T&&(b="italic");return c+("font-style:"+b+";font-weight:"+e+";")};function Ka(a,c,b,e,d,f,h,g){this.ca=a;this.Ha=c;this.a=b;this.b=e;this.Y=g||"BESb\uc5d0swy";this.ga=d;this.I={};this.Ka=f||5E4;this.ea=h||null;this.s=this.g=null;a=new Ha(this.a,this.Y);Ia(a);for(var l in S)S.hasOwnProperty(l)&&(c=new R(S[l],Q(this.b)),ha(a.a,a.b,Ja(c)),this.I[S[l]]=a.b.offsetWidth);ia(a.b)}var S={Xa:"serif",Wa:"sans-serif",Ta:"monospace"};function La(a,c,b){for(var e in S)if(S.hasOwnProperty(e)&&c===a.I[S[e]]&&b===a.I[S[e]])return!0;return!1}
function Ma(a){var c=a.g.b.offsetWidth,b=a.s.b.offsetWidth;c===a.I.serif&&b===a.I["sans-serif"]||a.ga.b&&La(a,c,b)?ea()-a.Ia>=a.Ka?a.ga.b&&La(a,c,b)&&(null===a.ea||a.ea.hasOwnProperty(a.b.getName()))?Na(a,a.ca):Na(a,a.Ha):Oa(a):Na(a,a.ca)}function Oa(a){setTimeout(da(function(){Ma(this)},a),25)}function Na(a,c){ia(a.g.b);ia(a.s.b);c(a.b)};function Pa(a,c,b,e){this.a=c;this.b=b;this.g=0;this.I=this.s=!1;this.ga=e;this.ea=a.b}
function Qa(a,c,b,e,d){if(0===c.length&&d)Ga(a.b);else for(a.g+=c.length,d&&(a.s=d),d=0;d<c.length;d++){var f=c[d],h=b[f.getName()],g=a.b,l=f;E(g.g,g.b.b("mti",l.getName(),Q(l).toString(),"loading"));Fa(g,"fontloading",l);f=new Ka(da(a.Y,a),da(a.ca,a),a.a,f,a.ea,a.ga,e,h);f.g=new Ha(f.a,f.Y);Ia(f.g);f.s=new Ha(f.a,f.Y);Ia(f.s);f.Ia=ea();h=f.g;g=new R(f.b.getName()+",serif",Q(f.b));ha(h.a,h.b,Ja(g));h=f.s;g=new R(f.b.getName()+",sans-serif",Q(f.b));ha(h.a,h.b,Ja(g));Ma(f)}}
Pa.prototype.Y=function(a){var c=this.b;ja(c.g,c.b.b("mti",a.getName(),Q(a).toString(),"loading"));ja(c.g,c.b.b("mti",a.getName(),Q(a).toString(),"inactive"));E(c.g,c.b.b("mti",a.getName(),Q(a).toString(),"active"));Fa(c,"fontactive",a);this.I=!0;Ra(this)};Pa.prototype.ca=function(a){var c=this.b;ja(c.g,c.b.b("mti",a.getName(),Q(a).toString(),"loading"));ma(c.g,c.b.b("mti",a.getName(),Q(a).toString(),"active"))||E(c.g,c.b.b("mti",a.getName(),Q(a).toString(),"inactive"));Fa(c,"fontinactive",a);Ra(this)};
function Ra(a){0==--a.g&&a.s&&(a.I?(a=a.b,ja(a.g,a.b.b("mti","loading")),ja(a.g,a.b.b("mti","inactive")),E(a.g,a.b.b("mti","active")),Fa(a,"active")):Ga(a.b))};mti.Ra=function(){this.ya='"'};mti.F=function(){this.ja=mti.F.g;this.K=mti.F.s};mti.F.g=["font-style","font-weight"];mti.F.s={"font-style":[["n","normal"]],"font-weight":[["4","normal"]]};mti.F.b=function(a,c,b){this.wa=a;this.Na=c;this.K=b};mti.F.b.prototype.compact=function(a,c){for(var b=0;b<this.K.length;b++)if(c==this.K[b][1]){a[this.wa]=this.K[b][0];break}};mti.F.b.prototype.expand=function(a,c){for(var b=0;b<this.K.length;b++)if(c==this.K[b][0]){a[this.wa]=this.Na+":"+this.K[b][1];break}};
mti.F.prototype.compact=function(a){var c=["n","4"];a=a.split(";");for(var b=0,e=a.length;b<e;b++){var d=a[b].replace(/\s+/g,"").split(":");if(2==d.length){var f=d[1];a:{for(var d=d[0],h=0;h<this.ja.length;h++)if(d==this.ja[h]){d=new mti.F.b(h,d,this.K[d]);break a}d=null}d&&d.compact(c,f)}}return c.join("")};
mti.F.prototype.expand=function(a){if(2!=a.length)return null;for(var c=[null,null],b=0,e=this.ja.length;b<e;b++){var d=this.ja[b];(new mti.F.b(b,d,this.K[d])).expand(c,a.substr(b,1))}return c[0]&&c[1]?c.join(";")+";":null};function Sa(a,c,b){this.s=a;this.ta=c;this.c=b;this.b=this.g=0}Sa.prototype.load=function(a){var c=a.context||this.s;this.a=new ga(this.s,c);c=new Da(this.a,c.document.documentElement,a);if(this.c.b.g){var b=this.ta,e=this.a,d=[],f;for(f in a)if(a.hasOwnProperty(f)){var h=b.b[f];h&&d.push(h(a[f],e))}a=a.timeout;this.b=this.g=d.length;a=new Pa(this.c,this.a,c,a);f=0;for(b=d.length;f<b;f++)e=d[f],e.Qa(this.c,da(this.I,this,e,c,a))}else Ga(c)};
Sa.prototype.I=function(a,c,b,e){var d=this;e?a.load(function(a,e,g){Ta(d,c,b,a,e,g)}):(a=0==--this.g,this.b--,a&&(0==this.b?Ga(c):Ea(c)),Qa(b,[],{},null,a))};function Ta(a,c,b,e,d,f){var h=0==--a.g;h&&Ea(c);setTimeout(function(){Qa(b,e,d||{},f||null,h)},0)};var Ua=window,Va=ya(),Wa=Ua.MonoTypeWebFonts=new Sa(window,new function(){this.b={}},Va);window.MonoTypeWebFonts.load=Wa.load;mti.qa=4E4;
mti.o=function(a,c,b,e,d){this.L=a;this.c=c;this.a=b;this.f=e;this.Da={};this.l=d;this.h=[];this.v=e.efg;this.m={};this.j=e.efg;this.L.mti_element_cache=[];this.da=[];this.ka=[];this.B=[];this.X={};this.O=[];this.S=[];this.la=0;this.version=this.H=void 0;this.sa={TTF:"truetype",WOFF:"woff",SVG:"svg",MTX:"truetype",OTF:"opentype",WOFF2:"woff2"};this.w={};this.xa=0;1==T.UseTextIndent?this.$="text-align:left;text-indent:-9999px;font-size:0px":this.$="visibility:hidden;";this.ba=this.f.reqSub||(void 0!==
T.EnableDSForAllFonts?T.EnableDSForAllFonts:!1);this.H=a=this.c.getName().toLowerCase();this.version=this.c.za;this.Fa="edge"==a?!0:!1;this.ma={EOT:2,SVG:11,OTF:13,TTF:1,WOFF:3,WOFF2:14}};mti.o.g="monotype";mti.o.b=!1;mti.o.prototype={Qa:function(a,c){var b=this,e=b.f.projectId,d;if(e){b.L.mti_element_cache=[];Xa(b);if(null!==b.l&&!1===b.ba)if(setTimeout(function(){document.documentElement.style.visibility=""},300),void 0!==T.PreLoadFonts&&b.isArray(T.PreLoadFonts)){var f=T.PreLoadFonts;d=[];for(var h=0;h<f.length;h++){var g=f[h].split(":"),l=g[0],g=1<g.length?g[1].split(","):"n4",k="n4";if(b.isArray(g)&&0<g.length)for(var m=0;m<g.length;m++)k=g[m],k=b.va(l,k),void 0!==k&&d.push(k);else k=b.va(l,k),void 0!==k&&
d.push(k)}Ya(b,d,"","",!0);c(!0)}else b.aa.call(b,!0,!0,!0),void 0===T.LoadAllFonts&&void 0===T.EnableCustomFOUTHandler||c(T.LoadAllFonts||T.EnableCustomFOUTHandler),b.na();else T.UseHybrid&&(setTimeout(function(){document.documentElement.style.visibility=""},700),T.EnableCustomFOUTHandler=!0,b.V(b.f.pfL,!1,!0)),d=function(){T.UseHybrid&&(window.MonoTypeWebFonts.addEvent("active",function(){Za(b,b.V,!1)}),window.MonoTypeWebFonts.addEvent("inactive",function(){Za(b,b.V,!1)}));b.na();b.ba?b.aa.call(b):
b.aa.call(b,!0);c(T.EnableCustomFOUTHandler)},!0===T.isAsync?T.onReady=d:(b.ba?$a(b,d):this.Aa(function(){b.aa.call(b,!0);c(T.EnableCustomFOUTHandler)}),b.f.enableOtf&&!b.ba&&$a(b,b.na.bind(b)));setTimeout(function(){document.documentElement.style.visibility=""},700);d=null;"function"===typeof b.L["__MonotypeConfiguration__"+e]&&(d=b.L["__MonotypeConfiguration__"+e]());if(void 0!==d||null!==d)loadAllFonts=d.loadAllFonts;var q=function(){var a=[];if(loadAllFonts)for(var c=0;c<b.f.pfL.length;c++){var d=
"n4",f=400,h="normal";void 0!=b.f.pfL[c].fontWeight&&void 0!=b.f.pfL[c].fontStyle&&(h=b.f.pfL[c].fontStyle,f=b.f.pfL[c].fontWeight,d=h.charAt(0)+f/100);var g=b.f.pfL[c].fontfamily,d=new R(g,d);d.fontfamily=g;d.fontWeight=f;d.fontStyle=h;a.push(d)}if(0<b.h.length||0<a.length){var l=[];b.h&&(l=b.h);loadAllFonts&&(l=a);b.L["__mti_fntLst"+e]=function(){for(var a=[],b=[],c=0;c<l.length;c++)a.push({fontfamily:l[c].P,fontStyle:l[c].T,fontWeight:l[c].W}),b.push(l[c]);return a}}else setTimeout(function(){q()},
0)};q()}else c(T.EnableCustomFOUTHandler)},aa:function(a,c,b){a=this;var e=!1,d={},f={};T.UseHybrid&&0<a.la?a.O.length!=a.la&&(e=!0):e=!0;if(e||null!=a.l){var f=new V(document.body,a.a,a.f.pfL),h=f.J(document.body),d=f.Z(),f=f.C;null!=a.l&&mti.bind(a.l,a.l.load,f)();if(c)"";else{c=a;for(var e=f,g=0;g<e.length;g++)for(var l in c.m)-1<c.a.D(e[g]).indexOf(l)&&(void 0==e[g].getAttribute("id"),c.a.M(e[g],l,c.m[l],c.bb,c.v))}}l=[];for(c=0;c<a.f.pfL.length;c++){var e=a.f.pfL[c],k,m,q,g=e.enableSubsetting,
u=e.enableOtf,v=e.contentIds,x=e.subsetOption;if(!e.enableSubsetting){void 0!=e.fontWeight&&void 0!=e.fontStyle&&(m=e.fontWeight,q=e.fontStyle,k=q.charAt(0)+m/100);var r=new R(e.fontfamily,k);r.fontfamily=e.fontfamily;r.fontWeight=void 0!=e.fontWeight?m:"4";r.fontStyle=void 0!=e.fontStyle?q:"n";r.enableSubsetting=g;r.contentIds=v;r.enableOtf=u;r.subsetOption=x;l.push(r);b&&d.push(r)}}k=l;m=null==k?0:k.length;q={};c=[];for(l=0;l<m;l+=1)q[k[l].P+"||"+k[l].W+"||"+k[l].T]=k[l];for(l in q)c.push(q[l]);
l=c;Ya(a,d,h,"",!0);b||Ya(a,l,h,"",!1);a.L.mti_element_cache=f},va:function(a,c){for(var b=0;b<this.f.pfL.length;b++){var e=this.f.pfL[b],d,f,h;void 0!=e.fontWeight&&void 0!=e.fontStyle&&(f=e.fontWeight,h=e.fontStyle,d=h.charAt(0)+f/100);if(e.fontfamily==a&&(this.j?c==d:1)){var b=e.enableSubsetting,g=e.enableOtf,l=e.contentIds,k=e.subsetOption,m=e.variationId,q=e.otfJsContentId;d=new R(e.fontfamily,d);d.fontfamily=e.fontfamily;d.fontWeight=void 0!=e.fontWeight?f:"4";d.fontStyle=void 0!=e.fontStyle?
h:"n";d.enableSubsetting=b;d.contentIds=l;d.enableOtf=g;d.subsetOption=k;d.variationId=m;d.otfJsContentId=q;return d}}}};MonoTypeWebFonts.ta.b[mti.o.g]=function(a){var c=ya(),b=new ga(window),e=null;a.enableOtf&&(e=new mti.Ua(b,c,a));c=new mti.o(window,c,b,a,e);if(a.reqSub||T.EnableDSForAllFonts||a.enableOtf){var d=new mti.ra(c);window.MonoTypeWebFonts.renderPartial=function(a,b){d.Oa(a,b)}}return c};
var ab={ec:"true",dfcURL:"http://api2.fonts.com/FontSubsetter.ashx",fontdataversion:"v2",sO:"true",ffArray:{safari:{"3.1":"ttf","5.1":"woff"},msafari:{1:"svg","4.2":"ttf","5.1":"woff","10.0":"woff2"},chrome:{3:"svg",4:"ttf",5:"woff",36:"woff2"},opera:{10:"ttf","11.10":"woff","26.0":"woff2"},msie:{4:"eot",9:"woff"},mozilla:{"3.5":"ttf","3.6":"woff","39.0":"woff2"},edge:{12:"woff",14:"woff2"}},bsmcArray:{safari:{"3.1":"2000","5.0":"15600"},msafari:{1:"15600"},chrome:{3:"15600"},opera:{10:"15600"},msie:{4:"1000",
9:"2080"},mozilla:{"3.5":"15600"},edge:{12:"15600"}},fctypeArray:{ttf:"1",eot:"2",woff:"3",svg:"11",otf:"13",woff2:"14"},specialChar:"%u201C %u201D %u2200 %u2202 %u2203 %u2205 %u2207 %u2208 %u2209 %u220B %u220F %u2211 %u2018 %u2019 %B0 %u2026 %u2122 %A9 %AE %u2014 %u2013 %A7 %B1 %B7 %u2032 %u2033 %u20AC %u2248 %u2260 %u2264 %u2265 %u221A %u221D %u2220 %u2225 %u2227 %u2228 %u2229 %u222A %u222B %u222E %u2234 %u2235 %u2236 %u2237 %u223D %u224C %u2261 %u226E %u226F %u2299 %u22A5 %u0391 %u0392 %u0393 %u0394 %u0395 %u0396 %u0397 %u0398 %u0399 %u039A %u039B %u039C %u039D %u039E %u039F %u03A0 %u03A1 %u03A3 %u03A4 %u03A5 %u03A6 %u03A7 %u03A8 %u03A9 %u221E %u2190 %u2191 %u2192 %u2193 %u2640 %u2642 + %22 %5C %23 %26 %3F %B7 %3B %3A".split(" ")};
function W(a,c){return void 0!=ab[c]?ab[c]:a.f[c]};function Ya(a,c,b,e,d){var f,h="TTF",g=a.f.projectId,l=W(a,"ec"),k=a.f.fcURL,m=W(a,"dfcURL"),q=document.getElementById("mti_fontface_"+a.f.projectId);null===q&&(q=a.a.createElement("style",{type:"text/css",id:"mti_fontface_"+a.f.projectId}));var u="",v=!1,x={},r={};a.m={};var p=null,y=null;void 0!=T.CustomDfcURL&&(m=T.CustomDfcURL);c||(c=[]);for(var n=0;n<c.length;n++){var z=c[n],t=c[n].fontfamily,B=c[n].contentIds,A=c[n].enableOtf,F=z.subsetOption;f=null;a.j&&(p=c[n].fontWeight,y=c[n].fontStyle,
f=y.charAt(0)+p/100,a.v=!0);d&&(null==f?new R(t):new R(t,f),a.h.push(c[n]));26<t.length&&!a.w&&(a.w[t+"_"+(null==f?"n4":f)]="mtiFont"+a.xa++);var h=a.U(B),G="";a.j?G=t+"_"+y.charAt(0)+p/100:G=t+"_n4";z=1==T.EnableDSForAllFonts?!0:z.enableSubsetting;var r=a,L=t,D=p,U=y,I=e,J=r.c.getName(),J=J.toLowerCase();f=r.c.za;"mozilla"==J.toLowerCase()&&"Unknown"==f&&(J="msie");f="?";l&&(f+=a.f.ck+"&");f+="fctypeId="+W(r,"fctypeArray")[h]+"&fcId="+B.TTF;f+="&projectId="+g;f+="&content=";var ra="";if(b){var ka=
null,la=bb(b,L,D,U);la?"":la="";var Z=la.split("::"),la=Z[0],Z=Z[1],L=I?L+I:L;r.v&&(L+="_"+U.charAt(0)+D/100);D=la.split("").sort().join("");D=eb(r,D,L,I);ka="";la&&(ka=D.replace('"',"").replace("?","").replace(";","").replace("#","").replace("&",""));if(ka&&0<ka.length||Z&&0<Z.length)ra+=("msie"==J?ka||"":(ka||""))+"BESb\uc5d0swyMm",void 0!==Z&&""!=Z&&(ra+=Z)}I=f+ra;J=W(r,"bsmcArray");D=r.H;"firefox"==D&&(D="mozilla");/ipad|ipod|iphone/.test(r.c.ia.toLowerCase())&&(r.H="msafari");
r=r.version.i;J=J[D];D="";U=void 0;for(U in J)parseFloat(r)>=parseFloat(U)&&(D=J[U]);r=D;f=I.length>r?Math.ceil(I.length/(r-f.length)):1;J=f;D="";if(1<J||e){if(null!==b){v=!0;x[G]||(x[G]=[]);if(b)var cb=b[G];if(cb){r=[];I="";f="n4";a.j&&(f=y.charAt(0)+p/100);D=I=(a.w[t+"_"+f]?a.w[t+"_"+f]:t)+(e?e:"");D+="_"+f;x[G].push(D);b[D]=cb;if(D=1<J?fb(a,B,g,!1,k,m,a.f.ck,I,p,y,b,h,A,e):fb(a,B,g,z,k,m,a.f.ck,I,p,y,b,h,A,e,F))A="",A=I,u=gb(a,A,"",u,p,y,A,D,h,B,!0,"",!1,!0,e,db,!1),r.push("'"+I+"'"),a.S[t+"_"+
f]=I;a.m[t+(a.j?"_"+f:"")]=r}}}else if(D=fb(a,B,g,z,k,m,a.f.ck,t+(e?e:""),p,y,b,h,A,e,!1,F)){var db="";(new V).fa(F)&&(h=hb(a));u=gb(a,t,"",u,p,y,t,D,h,B,!0,"",!1,!0,e,db,!1)}}if(!0===v||e)e?Xa(a,x,e):Xa(a,x);""!=u&&C(a.a,"head",q);q.styleSheet?""==q.styleSheet.cssText?q.styleSheet.cssText=u:q.styleSheet.cssText=q.styleSheet.cssText+"\n"+u:q.appendChild(document.createTextNode(u))}
function fb(a,c,b,e,d,f,h,g,l,k,m,q,u,v,x,r){function p(m,r){var p=a.f.env;d=d.replace("http://","").replace("https:///","");f=f.replace("http://","").replace("https:///","");d="https://"+d+(u?"ot/":"");f="https://"+f;if(r.fa(m))if(n=f+"?",n+=h+"&",n+="fctypeId="+("15"==W(a,"fctypeArray")[hb(a)]?"3":W(a,"fctypeArray")[hb(a)])+"&fcId="+c.TTF,n+="&env="+p+"&projectId="+b,void 0!=m){var p=m.unicode,t=m.text,I=m.lang,J=m.ot;void 0!=p&&(n+="&ranges="+p);void 0!=t&&(n+="&content="+t.replace('"',"%22").replace("'",
"%27").replace("#","%23").replace("?","%3F").replace("&","%26"));void 0!=I&&(n+="&languages="+I);void 0!=J&&(n+="&ot="+J)}else n="";else e?(n=f+"?",n+=h+"&",n+="fctypeId="+("15"==W(a,"fctypeArray")[q]?"3":W(a,"fctypeArray")[q])+"&fcId="+c.TTF,11==q&&(n+="&origId="+y),void 0!==p&&""!=p&&(n+="&env="+p)):(""!==a.ma[q.toUpperCase()]?d+=a.ma[q.toUpperCase()]+"/":d+=a.ma.WOFF+"/",n=d+y+"."+q.toLowerCase()+"?"+h,a.j?A=k.charAt(0)+l/100:A="n4",p=g+"_"+A,-1<a.a.indexOf(a.O,p)&&(n=""),0>a.a.indexOf(a.O,p)&&
!x&&!u&&!v&&a.O.push(p)),""!=n&&(n+="&projectId="+b,null!=q&&"SVG"==q.toUpperCase()&&(n+="#"+y));return n}var y=c[q.toUpperCase()],n,z,t,B,A,F;T.UseHybrid&&(F=X(g),a.j?(A=k.charAt(0)+l/100,F=X(g,A)):A="n4",1==e&&ib(F)&&(e=!1));F=new V;if(F.fa(r))n=p(r,F);else if(e||T.EnableDSForAllFonts){if(m){m=bb(m,g,l,k);if(null==m)return n="";if(m){B=m.split("").sort().join("");m=g;a.v&&(m+="_"+k.charAt(0)+l/100);B=eb(a,B,m,v);v&&(a.v?m=m.substring(0,m.length-8)+"_"+k.charAt(0)+l/100:m=m.substring(0,m.length-
5)+"_n4",a.X[m]=B);B=jb(a,B).split("::");m=B[0];B=B[1].replace(":","");m&&(t=m.replace('"',"").replace("?","").replace(";","").replace("#","").replace("&","").replace("%","%25"));if(t&&0<t.length||B&&0<B.length)z="&content="+(a.Fa?(t||""):t||"")+"BESb\uc5d0swyMm",""!=B&&(z+=B);n=p(r,F)+z}else return}}else p(r,F);return n}
mti.o.prototype.V=function(a,c,b){if(!(null!=a&&1>a.length)){var e=this.f.projectId,d=this.f.fcURL,f=this.f.ck,h="",g,l,k="msie"==this.c.getName()?!0:!1,m=!1,q={TTF:"truetype",WOFF:"woff",SVG:"svg",MTX:"truetype",OTF:"opentype",WOFF2:"woff2"},u=[];a=b?a:this.h;for(var v=0,x="n4",r=0;r<this.f.pfL.length;r++){var p=this.f.pfL[r],y=!1,n=p.fontfamily;p.enableSubsetting&&this.la++;if(b)y=!0;else for(v=0;v<a.length;v++)if(a[v].fontfamily==n&&(p.enableSubsetting||T.EnableDSForAllFonts)){if(this.v)a[v].fontWeight==
p.fontWeight&&a[v].fontStyle==p.fontStyle&&(y=!0,g=p.fontWeight,l=p.fontStyle,x=l.charAt(0)+g/100,z=X(n,x));else var z=X(n),y=!0;if(y){a.splice(v,1);break}}y&&(z=X(n),p.enableSubsetting||T.EnableDSForAllFonts)&&((void 0!=p.fontWeight&&void 0!=p.fontStyle&&(g=p.fontWeight,l=p.fontStyle,x=l.charAt(0)+g/100,z=X(n,x)),u.push(z),contentIdArray=p.contentIds,enableOtf=p.enableOtf,ib(z)||b)?ib(z)&&b&&(this.h.push(new R(n,x)),fFormat=this.U(contentIdArray),fontURL=fb(this,contentIdArray,e,!1,d,"",f,n,g,l,
null,fFormat,enableOtf,!1,!1),""!=fontURL&&(this.da.push(z),h=gb(this,n,"",h,g,l,n,fontURL,fFormat,contentIdArray,!0,"",!1,!0,!1,"",!1))):(m=!0,0>this.a.indexOf(this.da,z)&&(fFormat=this.U(contentIdArray),fontURL=fb(this,contentIdArray,e,!1,d,"",f,n,g,l,null,fFormat,enableOtf,!1,!0),""!=fontURL&&(this.da.push(z),h+='@font-face{\nfont-family:"'+z+'";',h+='\nsrc:url("'+fontURL+'")',null!=fFormat&&"EOT"==fFormat.toUpperCase()||"MTX"==fFormat.toUpperCase()||(p=q[fFormat.toUpperCase()],contentIdArray[fFormat.toUpperCase()]||
(p=q.TTF),h+=" format('"+p+"')"),h+=";}\n"))))}""!=h&&(b=this.a.getElementById("mti_fontface_"+e),null==b&&(b=this.a.createElement("style",{type:"text/css",id:"mti_fontface_"+this.f.projectId}),""!=h&&C(this.a,"head",b)),b.styleSheet?""!=b.styleSheet.cssText?(k=this.a.getElementById("mti_fontface_"+(c?"hybridAjaxIE_":"hybridIE_")+this.f.projectId),null==k&&(k=this.a.createElement("style",{type:"text/css",id:"mti_fontface_"+(c?"hybridAjaxIE_":"hybridIE_")+this.f.projectId}),""!=h&&C(this.a,"head",
k)),k.styleSheet.cssText=h):b.styleSheet.cssText=h:k?(k=this.a.getElementById("mti_fontface_"+(c?"hybridAjaxIE_":"hybridIE_")+this.f.projectId),null==k&&(k=this.a.createElement("style",{type:"text/css",id:"mti_fontface_"+(c?"hybridAjaxIE_":"hybridIE_")+this.f.projectId}),""!=h&&C(this.a,"head",k)),k.innerHTML+=h):b.innerHTML+=h);if(m){c=[];for(h=0;h<u.length;h++)c.push(new R(u[h]));Qa(new Pa(this.c,this.a,new Da(this.a,document.documentElement,{fontactive:function(a){if("_f"==a.substr(a.length-2)&&
!ib(a)){var b=new Date;a=a.replace(/\s+/g,"%20");b.setDate(b.getDate()+1);document.cookie=a+"="+("1; expires="+b.toUTCString())}}}),6E5),c,{},{},!1)}}};var T=window.MTIConfig||{ab:!1,Sa:!1,Va:!1};function V(a,c,b,e){this.Pa=a;this.a=c;this.Ma=b;this.R={};this.C=[];this.h=[];e?this.Ga=e:!1;this.Ea="img script noscript iframe object style param embed link meta head title br hr svg path".split(" ")}
V.prototype=function(){function a(a){var c=!1;void 0!=typeof a&&null!=a&&""!=a&&(void 0!=typeof a.lang&&null!=a.lang&&""!=a.lang?c=!0:void 0!=typeof a.unicode&&null!=a.unicode&&""!=a.unicode?c=!0:void 0!=typeof a.text&&null!=a.text&&""!=a.text?c=!0:void 0!=typeof a.ot&&null!=a.ot&&""!=a.ot&&(c=!0));return c}function c(a,e,d){if(void 0!==a&&null!==a&&""!==a&&a.tagName&&1===a.nodeType)for(0>d.a.indexOf(d.Ea,a.tagName.toLowerCase())&&(e?d.ua(a,e):d.ua(a)),a=a.firstChild;a;)c(a,e,d),a=a.nextSibling}return{ua:function(c,
e){var d=this.Ma,f=this.a.getComputedStyle(c),h=f.fontFamily,g="",l=f.fontStyle,k=0,m=0,q="",h=(h||"").replace(/^\s|\s$/g,"").replace(/'|"/g,"").replace(/,\s*/g,"|");if(""!=h)for(var h=h.split("|"),u="",k=0;k<h.length;k++)for(m=0;m<d.length;m++){var v=d[m],u=v.fontfamily,x,r,p=v.enableSubsetting,y=v.enableOtf,n=v.contentIds,z=v.subsetOption,t=!1,B=new RegExp("^("+h[k]+")$","ig");if(void 0!=v.fontWeight&&void 0!=v.fontStyle)x=v.fontWeight,r=v.fontStyle,q=r.charAt(0)+x/100,g="normal"==f.fontWeight?
400:"bold"==f.fontWeight?700:f.fontWeight;else{var A="h1 h2 h3 h4 h5 h6 strong b".split(" ");1==c.nodeType&&(g=0<=this.a.indexOf(A,c.tagName.toLowerCase())?400:"normal"==f.fontWeight?400:"bold"==f.fontWeight?700:400)}A=u.replace(/^\s|\s$/g,"");B.test(A)&&(void 0!=x||void 0!=r?g==x&&l==r&&(t=new R(A,q),t.fontfamily=A,t.fontWeight=x,t.fontStyle=r,t.enableSubsetting=p,t.contentIds=n,t.enableOtf=y,t.subsetOption=z,this.h.push(t),this.C.push(c),t=!0):(q="n4",t=new R(A),t.fontfamily=A,t.fontWeight=g/100,
t.fontStyle=l.charAt(0),t.enableSubsetting=p,t.contentIds=n,t.enableOtf=y,t.subsetOption=z,this.h.push(t),this.C.push(c),t=!0),t&&(1==T.EnableCustomFOUTHandler&&E(c,e?"mti_font_element"+e:"mti_font_element"),p=c.getAttribute("style"),(p=null!=p?"string"==typeof p?p:"cssText"in p?p.cssText:"":"")&&-1<this.a.indexOf(p,"font-weight")&&-1<this.a.indexOf(p,"font-style")?u+="_"+l.charAt(0)+g/100:u+=1<q.length?"_"+q:"",!v.enableSubsetting&&!T.EnableDSForAllFonts||a(z)||(v="",v=na(this.a,c),this.R[u.replace(/^\s|\s$/g,
"")]&&(v+=this.R[u.replace(/^\s|\s$/g,"")]),this.R[u.replace(/^\s|\s$/g,"")]=v)))}},J:function(a,e){c(this.Pa,e,this);var d=!1,f;for(f in this.R)if(d=!0,this.Ga)break;else this.R[f]=ua(this.R[f]);return d?this.R:null},Z:function(){var a=this.h,c=null==a?0:a.length,d={},f,h=[];for(f=0;f<c;f+=1)d[a[f].P+"||"+a[f].W+"||"+a[f].T]=a[f];for(f in d)h.push(d[f]);return this.h=h},$a:function(){return this.C},fa:a}}();mti.o.prototype.U=function(a){var c=W(this,"ffArray"),b=this.H,e=this.version.i+this.version.G/10;"firefox"==this.H&&(b="mozilla");/ipad|ipod|iphone/.test(this.c.ia.toLowerCase())&&(b="msafari");var c=c[b],b="",d;for(d in c)parseFloat(e)>=parseFloat(d)&&a[c[d].toUpperCase()]&&(b=c[d]);return b};function kb(){for(var a="",c=0;5>c;c++)a+="abcdefghijklmnopqrstuvwxyz".charAt(Math.floor(26*Math.random()));return a}
function lb(a,c){for(var b=0,e=0,d=!1,f=a.length,h=c.length,b=0;b<h;b++){d=!1;for(e=0;e<f;e++)c[b]==a[e]&&(d=!0);if(0==d&&e==f)return 0}return 1}mti.o.prototype.pa=function(a){if((a.ctrlKey||a.metaKey)&&116==a.keyCode){a.preventDefault();a=document.cookie.split(";");for(var c=1;c<=a.length;c++){var b=a[c-1].split("="),e=b[0].substr(b[0].length-2);"1"==b[1]&&"_f"==e&&(document.cookie=b[0]+"=;expires=Thu, 01 Jan 1970 00:00:00 GMT")}document.location.reload(!0)}};
function jb(a,c){var b=W(a,"specialChar"),e=b.length.toString().length;if(c&&"string"==typeof c){for(var d="",f=c.length,h=null,g="",l=[],k=0;k<f;k++)if(h=c.charAt(k),-1<a.a.indexOf(b,escape(h))){if(-1==a.a.indexOf(l,h)){l.push(h);h=a.a.indexOf(b,escape(h));if(h.toString().length<e)var m=Array(1+e).join("0"),h=(m+h).slice(-m.length);g+=h}}else-1==a.a.indexOf(d,h)&&(d+=h);return d+"::"+g}return""}
function bb(a,c,b,e){var d="";c=void 0!=b&&void 0!=e?c+("_"+e.charAt(0)+b/100):c+"_n4";a&&a[c]&&(d=a[c]);return 0<d.length?d:null}mti.o.prototype.Z=function(){return this.h};w=mti.o.prototype;w.load=function(a){a(this.h,this.Da)};
function Xa(a,c,b){var e=new Ca("-"),d=a.a.createElement("style",{type:"text/css",id:"mti_stylesheet_"+(b?"Aj_":"")+a.f.projectId}),f="";if(1==T.EnableCustomFOUTHandler||1==T.UseHybrid){for(var h=a.f.pfL,f=f+(".mti-loading .mti_font_element"+(b?"_Aj":"")+"{"+a.$+"}\n"),g=0;g<h.length;g++){var l=h[g].fontfamily,k="4",m="n";a.j&&(k=h[g].fontWeight/100,m=h[g].fontStyle.charAt(0));b&&(l=l+b);l&&(f+="."+e.b("mti",l,m+k,"loading")+" .mti_font_element"+(b?b:"")+"{"+a.$+"}\n")}f+=".mti_hide_element{"+a.$+
"}"}for(g in a.f.selectorFontMap)if(e=a.f.selectorFontMap[g],l=e.familyName,a.j?(m=e.fontStyle,k=e.fontWeight):(m="normal",k="400"),c&&c[l]&&0<c[l].length&&(l=c[l].join("','")),b||(f=gb(a,l,g,f,k,m,"","","","",!1,e,!0)),1==T.EnableCustomFOUTHandler)for(m in f+="/*fout specific code:*/\n",k=g.split(","),m=void 0,k)f+=".mti-loading "+k[m]+"{"+a.$+"}\n";""!=f&&C(a.a,"head",d);d.styleSheet?d.styleSheet.cssText=f:d.appendChild(document.createTextNode(f))}
function gb(a,c,b,e,d,f,h,g,l,k,m,q,u,v,x,r,p){1<a.a.indexOf(h,x)?x="":"";v?e+='@font-face{\nfont-family:"'+h+(x?x:"")+(r?r:"")+'";':"";v?"":e+=b+"{font-family:'"+c+"';";a.j&&!p&&(e=e+("\n font-style:"+f+";")+("\n font-weight:"+d+";"));g?e+='\nsrc:url("'+g+'")':"";m?(c=e,null!=l&&"EOT"==l.toUpperCase()||"MTX"==l.toUpperCase()||(b=a.sa[l.toUpperCase()],k[l.toUpperCase()]||(b=a.sa.TTF),c+=" format('"+b+"')"),e=c):"";u?(l=e,null!=a.l&&(k=q.otf,q=q.vrnt,k&&null!=k&&""!=k&&(l+=a.l.Za(k,q))),e=l):"";return e+=
";}\n"}w.Aa=function(a){function c(){document.body?a():setTimeout(c,0)}c()};w.U=function(a){var c=W(this,"ffArray"),b=this.H,e=this.version.i+this.version.G/10;"firefox"==this.H&&(b="mozilla");/ipad|ipod|iphone/.test(this.c.ia.toLowerCase())&&(b="msafari",e=this.c.La.i);var c=c[b],b="",d;for(d in c)parseFloat(e)>=parseFloat(d)&&a[c[d].toUpperCase()]&&(b=c[d]);""===b&&(b="ttf");return b};
function hb(a){var c=W(a,"ffArray"),b=a.H,e=a.version.i+a.version.G/10;"firefox"==a.H&&(b="mozilla");/ipad|ipod|iphone/.test(a.c.ia.toLowerCase())&&(b="msafari");a=c[b];var c="",d;for(d in a)parseFloat(e)>=parseFloat(d)&&(c=a[d]);""===c&&(c="ttf");return c}w.fa=function(a){var c=!1;void 0!=typeof a&&null!=a&&""!=a&&(void 0!=typeof a.lang&&null!=a.lang&&""!=a.lang?c=!0:void 0!=typeof a.unicode&&null!=a.unicode&&""!=a.unicode?c=!0:void 0!=typeof a.text&&null!=a.text&&""!=a.text&&(c=!0));return c};
w.isArray=function(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)};function X(a,c){void 0===c&&(c="n4");return a+"_"+c+"_f"}function mb(a,c){for(var b in c)if(a==c[b])return b;return!1};function nb(a,c,b){if(!window.MutationObserver||b){var e="string"==typeof c?document.getElementById(c):c;if(null!==e){b=!0;a.h=[];var d=a.f.projectId,f=a.f.fcURL,h=a.f.ck,g="",l,k,m={TTF:"truetype",WOFF:"woff",SVG:"svg",MTX:"truetype",OTF:"opentype",WOFF2:"woff2"};b=!0;if(T.UseHybrid){b=!1;var q=a.a.getElementById("mti_fontface_"+d);null==q&&(q=a.a.createElement("style",{type:"text/css",id:"mti_fontface_"+d}),C(a.a,"head",q));var u=e.getAttribute("data-mtiFont"),v=a.a.getComputedStyle(e);null==u&&
(u=v.fontFamily.replace(/^\s|\s$/g,"").replace(/'|"/g,""));for(var x=[],r=0;r<a.f.pfL.length;r++)x.push(a.f.pfL[r].fontfamily);if(e.hasChildNodes&&0>a.a.indexOf(x,u))for(r=e.childNodes,y=0;y<r.length&&!(1==r[y].nodeType&&(u=a.a.D(r[y]).replace(/^\s|\s$/g,"").replace(/'|"/g,""),-1<a.a.indexOf(x,u)));y++);for(var x="normal"==v.fontWeight?"400":"bold"==v.fontWeight?"700":v.fontWeight,v=v.fontStyle,r=v.charAt(0)+x/100,p=u.split(","),y=0;y<p.length;y++){b=X(p[y]);for(var n,z=!1,r=0;r<a.f.pfL.length;r++){n=
a.f.pfL[r];var t=n.fontfamily;if(p[y]==t&&n.enableSubsetting)if(void 0!=n.fontWeight&&void 0!=n.fontStyle){if(l=n.fontWeight,k=n.fontStyle,v==n.fontStyle&&x==n.fontWeight){z=!0;r=k.charAt(0)+l/100;b=X(t,r);a.h.push(new R(t,r));break}}else{a.h.push(new R(t));z=!0;break}}if(ib(b)&&z){b=!1;contentIdArray=n.contentIds;enableOtf=n.enableOtf;fFormat=a.U(contentIdArray);n=t;fontURL=fb(a,contentIdArray,d,!1,f,"",h,n,l,k,null,fFormat,enableOtf);""!=fontURL&&(g+='@font-face{\nfont-family:"'+n+'";',void 0!=
l&&void 0!=k&&(g+="\nfont-style:"+k+";",g+="\nfont-weight:"+l+";"),g+='\nsrc:url("'+fontURL+'")',null!=fFormat&&"EOT"==fFormat.toUpperCase()||"MTX"==fFormat.toUpperCase()||(l=m[fFormat.toUpperCase()],contentIdArray[fFormat.toUpperCase()]||(l=m.TTF),g+=" format('"+l+"')"),g+=";}\n");q.styleSheet?q.styleSheet.cssText+=g:q.innerHTML+=g;a.X[n]=eb(a,"",n);e.style.fontFamily=""+u;e.removeAttribute("data-mtiFont");g="";if(e.hasChildNodes())for(g=e.childNodes,l=0;l<g.length;l++)1==g[l].nodeType&&g[l].getAttribute("data-mtiFont")&&
(g[l].style.fontFamily=g[l].getAttribute("data-mtiFont"),g[l].removeAttribute("data-mtiFont"));if(null!=a.l){var B=new V(document.getElementById(c).parentElement,a.a,a.f.pfL);B.J({},A);mti.bind(a.l,a.l.ha,B.C)()}break}else b=!0}}if(b){var A=kb(),F=B=null,G=[],L=[],D=null!=e?e.parentElement:document.body;(function(){B=new V(D,a.a,a.f.pfL);F=B.J({},A);var b=[];if(void 0!=F)for(var d in F)d+=A,b.push(new R(f));a.L.mti_element_cache=B.C;Ya(a,B.Z(),F,A,!0);b=B.C;null!=a.l&&(d=[],d.push(e),mti.bind(a.l,
a.l.ha,d)());for(d=0;d<b.length;d++)for(var f in a.m)-1<a.a.indexOf(a.a.D(b[d]),f)&&(b[d].getAttribute("id")==c||b[d]==c?a.a.M(b[d],f,a.m[f],!1,a.v):ta(e,b[d])&&-1<a.a.indexOf(a.a.D(b[d]).replace(/'|"/g,""),f)&&a.a.M(b[d],f,a.m[f],!1,a.v));d=null==a.m[f]?0:a.m[f].length;if(0<a.h.length)for(b=0;b<a.h.length;b++)f=a.h[b].getName()+A,d=null,a.v&&(d=Q(a.h[b])),f=null==d?new R(f):new R(f,d),G.push(f);else for(b=0;b<d;b++)a.v?G.push(new R(a.m[f][b],"i6")):G.push(new R(a.m[f][b])),-1==a.a.indexOf(a.ka,f)&&
(a.ka.push(f),a.v?L.push(new R(a.m[f][b],"i6")):L.push(new R(a.m[f][b])))})();1==T.RemoveMTIClass&&setTimeout(function(){ob(a,"mti_font_element"+A)},fa.qa);b={};T.UseHybrid&&0<G.length&&(b.fontactive=function(){Za(a,a.V,!0)},b.fontinactive=function(){Za(a,a.V,!0)});1==T.EnableCustomFOUTHandler&&Qa(new Pa(a.c,a.a,new Da(a.a,document.documentElement,b),fa.qa),G,{},{},!1)}}}}mti.ra=function(a){this.Ja=a};mti.ra.prototype={Oa:function(a,c){nb(this.Ja,a,c)}};
mti.o.prototype.na=function(){var a=this,c="",b="img script noscript iframe object style param embed link meta head title br hr svg path".split(" ");if(window.MutationObserver){var e=new MutationObserver(function(b){b.forEach(function(b){if("characterData"==b.type)null!=b.target.parentNode&&(d=b.target.parentNode,"undefined"!==typeof d.getAttribute("isRender")&&"true"!==d.getAttribute("isRender")?(d.setAttribute("isRender","true"),null!=b.target.parentNode.id&&void 0!=typeof b.target.parentNode.id&&
"undefined"!==typeof document.getElementById(b.target.parentNode.id)&&null!=document.getElementById(b.target.parentNode.id)&&(c=document.getElementById(b.target.parentNode.id).getAttribute("data-mti-otf")),void 0!=typeof c&&"mti-otf"!=c&&Y(a,b.target.parentNode)):setTimeout(function(){d.removeAttribute("isRender")},0));else if("attributes"==b.type)if("style"==b.attributeName){var d=b.target;""==d.style.fontFamily&&""==d.style.fontWeight&&""==d.style.fontStyle||"BESb\uc5d0swy"==d.innerHTML||"BESbswy"==
d.innerHTML||("undefined"!==typeof d.getAttribute("isRender")&&"true"!==d.getAttribute("isRender")?(d.setAttribute("isRender","true"),null!=d.id&&""!=d.id&&void 0!=typeof d.id?"undefined"!==typeof document.getElementById(d.id)&&null!=document.getElementById(d.id)&&(c=document.getElementById(d.id).getAttribute("data-mti-otf")):null!=d&&""!=d&&void 0!=typeof d&&(c=d.getAttribute("data-mti-otf")),d=null!=d.id?d.id:d,"mti-otf"!=c&&""!=d&&Y(a,d)):setTimeout(function(){d.removeAttribute("isRender")},0))}else"class"==
b.attributeName&&pb(qb(b.target.classList))?Y(a,b.target):"id"==b.attributeName&&-1<b.target.id.indexOf("mtiSelector")&&Y(a,b.target);else if("childList"==b.type&&0<b.addedNodes.length)for(var e=0;e<b.addedNodes.length;e++)if(d=b.addedNodes[e],3==d.nodeType&&(d=d.parentNode),"undefined"!==typeof d&&null!=d&&3!=d.nodeType){var l=d.tagName;"HTML"!=l&&"HEAD"!=l&&"TITLE"!=l&&"STYLE"!=l&&"LINK"!=l&&"META"!=l&&"BASE"!=l&&"IMG"!=l&&"HR"!=l&&"BR"!=l&&"BESb\uc5d0swy"!=d.innerHTML&&"BESbswy"!=d.innerHTML&&
"undefined"!==typeof d.className&&"function"===typeof d.className.indexOf&&-1==d.className.indexOf("firebugLayoutBox")&&(null!=d.id&&""!=d.id&&void 0!=typeof d.id?null!=document.getElementById(d.id)&&(c=document.getElementById(d.id).getAttribute("data-mti-otf")):null!=d&&""!=d&&void 0!=typeof d&&(c=d.getAttribute("data-mti-otf")),d="undefined"!==typeof d.id&&null!=d.id&&""!=d.id?d.id:d,"mti-otf"!=c&&""!=d&&Y(a,d))}});rb(a,!0)});document.body&&e.observe(document.body,{childList:!0,characterData:!0,
subtree:!0,attributes:!0,attributeOldValue:!0,attributeFilter:["style","class","id"]})}else e=function(a,c){var b=document;b.addEventListener?b.addEventListener(a,c,!1):b.attachEvent("on"+a,c)},e("DOMNodeInserted",function(d){d=d.target;if(1>d.childNodes.length||""==d.innerHTML)return!1;void 0!=typeof d&&null!=d&&3==d.nodeType&&(d=void 0!==d.parentElement?d.parentElement:d.parentNode);if(0<a.a.indexOf(b,d.nodeName.toLowerCase()))return!1;if(void 0!=typeof d&&null!=d&&1==d.nodeType){var e=d.tagName;
"HTML"!=e&&"HEAD"!=e&&"TITLE"!=e&&"STYLE"!=e&&"LINK"!=e&&"META"!=e&&"BASE"!=e&&"IMG"!=e&&"HR"!=e&&"BR"!=e&&"BESb\uc5d0swy"!=d.innerHTML&&"BESbswy"!=d.innerHTML&&(void 0!=typeof d.id&&null!=d.id&&""!=d.id?"undefined"!==typeof document.getElementById(d.id)&&null!=document.getElementById(d.id)&&(c=document.getElementById(d.id).getAttribute("data-mti-otf")):void 0!=typeof d.getAttribute&&void 0!=typeof d&&null!=d&&""!=d&&(c=d.getAttribute("data-mti-otf")),"mti-otf"!=c&&""!=d&&(Y(a,d),rb(a,!1)))}}),e("DOMAttrModified",
function(b){if("style"==b.attrName){var e=b.target;"BESb\uc5d0swy"!=e.innerHTML&&"BESbswy"!=e.innerHTML&&("undefined"!==typeof e.getAttribute("isRender")&&"true"!==e.getAttribute("isRender")?(e.setAttribute("isRender","true"),void 0!=typeof e.id&&null!=e.id&&""!=e.id?void 0!=typeof document.getElementById(e.id)&&null!=document.getElementById(e.id)&&(c=document.getElementById(e.id).getAttribute("data-mti-otf")):void 0!=typeof e.getAttribute("data-mti-otf")&&null!=e&&""!=e&&(c=e.getAttribute("data-mti-otf")),
"mti-otf"!=c&&""!=e&&(Y(a,e),rb(a,!1))):setTimeout(function(){e.removeAttribute("isRender")},0))}else"class"==b.attrName&&pb(qb(b.target.className))?(Y(a,b.target),rb(a,!1)):"id"==b.attrName&&-1<b.target.id.indexOf("mtiSelector")&&(Y(a,b.target),rb(a,!1))}),e("DOMCharacterDataModified",function(b){b=b.target;void 0!=typeof b&&null!=b&&3==b.nodeType&&(b=b.parentElement);if(void 0!=typeof b&&null!=b&&1==b.nodeType){var e=b.tagName;"HTML"!=e&&"HEAD"!=e&&"TITLE"!=e&&"STYLE"!=e&&"LINK"!=e&&"META"!=e&&
"BASE"!=e&&"IMG"!=e&&"HR"!=e&&"BR"!=e&&"BESb\uc5d0swy"!=b.innerHTML&&"BESbswy"!=b.innerHTML&&(void 0!=typeof b.id&&null!=b.id&&""!=b.id?null!=document.getElementById(b.id)&&(c=document.getElementById(b.id).getAttribute("data-mti-otf")):void 0!=typeof b&&null!=b&&""!=b&&(c=b.getAttribute("data-mti-otf")),"mti-otf"!=c&&""!=b&&(Y(a,b),rb(a,!1)))}})};
function Y(a,c){if(void 0!=typeof c&&null!=c){var b,e,d="",f=!1;"string"==typeof c?(b=document.getElementById(c),null!=b&&(e=b.parentNode),null!=e&&(d=b.getAttribute("id")),-1==a.a.indexOf(a.B,c)&&-1==a.a.indexOf(a.B,d)&&(a.B.push(c),f=!0)):-1==a.a.indexOf(a.B,c)&&-1==a.a.indexOf(a.B,c.parentElement)&&(a.B.push(c),f=!0);f&&1==T.EnableCustomFOUTHandler&&(c="string"==typeof c?document.getElementById(c):c,void 0!=typeof c&&null!=c&&1==c.nodeType&&sb(a,c).u&&tb(a,c))}}mti.o.prototype.oa=null;
function rb(a,c){var b=50;c||(b=0);a.f.enableOtf&&(b=0);null!=a.oa&&clearTimeout(a.oa);a.oa=setTimeout(function(){if(-1<a.B.length){var b="",c=a.B.length;if(!(1>c)){for(var f=0;f<c;f++){var h="string"==typeof a.B[f]?document.getElementById(a.B[f]):a.B[f];if(void 0!=typeof h&&null!=h){var b=na(a.a,h),g=new V(h,a.a,a.f.pfL),l=g.J(h),g=g.C,k=sb(a,h);k.u?""!=b?ub(a,a.B[f],b,k,l,g):(b="_n4",a.j&&(b=k.fontStyle.charAt(0)+k.fontWeight/100),null!=l&&(b=l[k.N+b],""!=b&&ub(a,a.B[f],b,k,l,g))):!k.u&&null!=h&&
h.hasChildNodes&&(k=vb(a,h),b=na(a.a,k.node),g=new V(k.node,a.a,a.f.pfL),l=g.J(k.node),g=g.C,k.u&&ub(a,k.node,b,k,l,g))}}a.B=[]}}},b)}
function sb(a,c){if(1!=c.nodeType)return{u:!1};var b=a.a.getComputedStyle(c),e="test",d="normal",f="100";if(void 0!=typeof b&&null!=b)if(e=b.fontFamily,d=b.fontStyle,f="normal"==b.fontWeight?"400":"bold"==b.fontWeight?"700":b.fontWeight,b=null!=e?e.split(","):"",b instanceof Array)for(e=0;e<b.length;e++)for(var h=0;h<a.f.pfL.length;h++){var g=a.f.pfL[h],l=g.fontfamily,k=g.enableSubsetting,m=g.fontStyle,q=g.fontWeight,g=g.enableOtf;if(l==H(b[e])&&(k||g))if(a.j){if(m==d&&q==f)return{u:!0,N:l,fontWeight:f,
fontStyle:d}}else return{u:!0,N:l}}else for(e=0;e<a.f.pfL.length;e++)if(g=a.f.pfL[e],l=g.fontfamily,k=g.enableSubsetting,m=g.fontStyle,q=g.fontWeight,g=g.enableOtf,k||g)if(a.v){if(m==d&&q==f)return{u:!0,N:l,fontWeight:f,fontStyle:d}}else if(l==H(b))return{u:!0,N:l};return{u:!1}}function vb(a,c){var b={u:!1,N:"testFont"};if(1==c.nodeType&&(b=sb(a,c),b.u))return b.node=c,b;for(var e=c.childNodes,d=e.length,f=0;f<d;f++){var h=e[f];if(1==h.nodeType&&(b=vb(a,h),b.u))break}return b}
function wb(a,c,b){var e="string"==typeof c?document.getElementById(c):c;if(null!==e){var d=!0,f=[];a.h=[];var h=a.f.projectId,g=a.f.fcURL,l=a.f.ck,k="",m,q,d=!0;if(T.UseHybrid){var d=!1,u=a.a.getElementById("mti_fontface_"+h);null==u&&(u=a.a.createElement("style",{type:"text/css",id:"mti_fontface_"+h}),C(a.a,"head",u));var v=e.getAttribute("data-mtiFont"),x=a.a.getComputedStyle(e);null==v&&(v=x.fontFamily.replace(/^\s|\s$/g,"").replace(/'|"/g,""));for(var r=[],p=0;p<a.f.pfL.length;p++)r.push(a.f.pfL[p].fontfamily);
if(e.hasChildNodes&&0>a.a.indexOf(r,v))for(p=e.childNodes,n=0;n<p.length&&!(1==p[n].nodeType&&(v=a.a.D(p[n]).replace(/^\s|\s$/g,"").replace(/'|"/g,""),-1<a.a.indexOf(r,v)));n++);for(var r="normal"==x.fontWeight?"400":"bold"==x.fontWeight?"700":x.fontWeight,x=x.fontStyle,y=x.charAt(0)+r/100,v=v.split(","),n=0;n<v.length;n++){for(var z,p=0;p<a.f.pfL.length;p++){z=a.f.pfL[p];var t=z.fontfamily,B=X(t);if(v[n]==t&&z.enableSubsetting)if(a.j){if(m=z.fontWeight,q=z.fontStyle,x==z.fontStyle&&r==z.fontWeight){y=
q.charAt(0)+m/100;B=X(t,y);a.h.push(new R(t,y));f.push(new R(t,y));break}}else{y="n4";a.h.push(new R(t));f.push(new R(t));break}}ib(B)&&(d=!1,-1==a.a.indexOf(a.O,t+"_"+y)&&(contentIdArray=z.contentIds,enableOtf=z.enableOtf,fFormat=a.U(contentIdArray),fontURL=fb(a,contentIdArray,h,!1,g,"",l,t,m,q,null,fFormat,enableOtf),""!=fontURL&&(k+='@font-face{\nfont-family:"'+t+'";',a.j&&(k+="\nfont-style:"+q+";",k+="\nfont-weight:"+m+";"),k+='\nsrc:url("'+fontURL+'")',k+=";}\n",a.X[t+"_"+y]=eb(a,"",t+"_"+y))));
if(""!=k){u.styleSheet?u.styleSheet.cssText+=k:u.innerHTML+=k;e.removeAttribute("data-mtiFont");p="";if(e.hasChildNodes())for(var p=e.childNodes,A=0;A<p.length;A++)1==p[A].nodeType&&p[A].getAttribute("data-mtiFont")&&(p[A].style.fontFamily=p[A].getAttribute("data-mtiFont"),p[A].removeAttribute("data-mtiFont"));if(null!=a.l){var F=new V(null!=e&&e!=document.body?e.parentElement:document.body,a.a,a.f.pfL);F.J({},G);mti.bind(a.l,a.l.ha,F.C)()}}else d=!0}}if(d){var G=kb(),L=F=null,f=[],D=[],U=null!=e&&
e!=document.body?e.parentElement:document.body;if(null==e.parentElement||b)U=document.body;(function(){F=new V(U,a.a,a.f.pfL);L=F.J({},G);if(void 0!=L)for(var b in L)26<b.length&&(a.w[b]||(a.w[b]="mtiFont"+a.xa++)),void 0!==a.w[b]&&""!==a.w[b]&&(b=a.w[b]),b+=G;a.L.mti_element_cache=F.C;Ya(a,F.Z(),L,G,!0);b=F.C;null!=a.l&&mti.bind(a.l,a.l.ha,b)();for(var d,h,g=0;g<b.length;g++){var l=a.a.getComputedStyle(b[g]),k;for(k in a.m)a.j&&(d=k.slice(-2),k=k.slice(0,-3),h=l.fontWeight,h=l.fontStyle.charAt(0)+
h/100),-1<a.a.indexOf(a.a.D(b[g]),k)&&(a.j?d==h:1)&&(b[g].getAttribute("id")==c||b[g]==c?a.a.M(b[g],k,a.m[k+(a.j?"_"+d:"")],!1,a.v):ta(e,b[g])&&-1<a.a.indexOf(a.a.D(b[g]).replace(/'|"/g,""),k)&&(a.j?d==h:1)&&a.a.M(b[g],k,a.m[k+(a.j?"_"+d:"")],!1,a.v))}b=null==a.m[k]?0:a.m[k].length;if(0<a.h.length)for(d=0;d<a.h.length;d++)a.h[d].enableSubsetting&&(k="n4",a.j&&(k=Q(a.h[d])),b=(void 0!==a.w[a.h[d].getName()+"_"+k]?a.w[a.h[d].getName()+"_"+k]:a.h[d].getName())+G,k=null!=k?new R(b,k):new R(b),f.push(k));
else for(d=0;d<b;d++)a.j?f.push(new R(a.m[k][d],"i6")):f.push(new R(a.m[k][d])),-1==a.a.indexOf(a.ka,k)&&(a.ka.push(k),a.j?D.push(new R(a.m[k][d],"i6")):D.push(new R(a.m[k][d])))})();1==T.RemoveMTIClass&&setTimeout(function(){ob(a,"mti_font_element"+G)},5E3);b={};0<f.length&&(b.fontactive=function(b,c,d){T.UseHybrid&&Za(a,a.V,!0);for(var e=0;e<window.MonoTypeWebFonts._fontActiveEventList.length;e++)d=b.slice(0,-5),window.MonoTypeWebFonts._fontActiveEventList[e].call(window.MonoTypeWebFonts,b,c,d)},
b.inactive=function(a,b,c){for(var d=0;d<window.MonoTypeWebFonts._inActiveEventList.length;d++)c=a.slice(0,-5),window.MonoTypeWebFonts._inActiveEventList[d].call(window.MonoTypeWebFonts,a,b,c)},b.fontloading=function(a,b,c){for(var d=0;d<window.MonoTypeWebFonts._fontLoadingEventList.length;d++)c=a.slice(0,-5),window.MonoTypeWebFonts._fontLoadingEventList[d].call(window.MonoTypeWebFonts,a,b,c)},b.active=function(){for(var a=0;a<window.MonoTypeWebFonts._activeEventList.length;a++)window.MonoTypeWebFonts._activeEventList[a].call(window.MonoTypeWebFonts)});
1==T.EnableCustomFOUTHandler&&Qa(new Pa(a.c,a.a,new Da(a.a,document.documentElement,b),5E3),f,{},{},!1)}}}
function ub(a,c,b,e,d,f){var h=c;"string"==typeof c&&(h=document.getElementById(h));e=c==e.node?!0:!1;var g="",g="";if(null!=d)for(var l in d){if(""!=d[l]){var k=l.slice(0,-3),m=l.slice(-2),q=k;void 0!==a.w[l]&&(k=a.w[l]);b+=void 0!==d[k+"_"+m]?d[k+"_"+m]:"";var g=ua(b),g=g.split("").sort().join(""),g=eb(a,g,k+"abcde"+(a.j?"_"+m:""),!0),u=a.X[k+"_"+m];if(-1==a.a.indexOf(a.O,l))if(T.UseHybrid)if(ib(X(q,m)))wb(a,c,e);else if(g!=u){for(var v in f)g=sb(a,f[v]),g.u&&(b=na(a.a,f[v]),""!=b&&(g=eb(a,"",k+
"abcde_"+m,!0),q=ua(b).split("").sort().join(""),g=ua(g),lb(g,q)||wb(a,f[v],e)));wb(a,c,e)}else null!=a.l&&xb(a,c),-1<a.da.indexOf(l+"_f")&&-1==a.O.indexOf(l)&&(textCollector=new V(h,a.a,a.f.pfL),d=textCollector.J({}),Ya(a,textCollector.Z(),d));else if(g!=u)wb(a,c,e);else{k=a.a.D(h);m=h.getAttribute("data-mtiFont");u=!0;g=sb(a,h);g.u&&a.j&&(u=a.a.getComputedStyle(h),k=u.fontFamily,fntStyle=u.fontStyle,fntWeight=u.fontWeight,u=fntStyle==g.fontStyle&&fntWeight==g.fontWeight?!0:!1);if(-1==k.indexOf(a.S[l])&&
-1<k.indexOf(m)&&0==a.S[l].indexOf(m)&&u)a.a.M(h,q,a.S[l],!1,!1);else for(v in f)g=sb(a,f[v]),g.u&&g.N===q&&(k=a.a.D(f[v]),u=!0,m="n4",a.j&&(u=a.a.getComputedStyle(f[v]),k=u.fontFamily,fntStyle=u.fontStyle,fntWeight=u.fontWeight,m=g.fontStyle.charAt(0)+g.fontWeight/100,u=fntStyle==g.fontStyle&&fntWeight==g.fontWeight?!0:!1),void 0!==a.S[q+"_"+m]&&-1==k.indexOf(a.S[q+"_"+m])&&u&&a.a.M(f[v],q,a.S[q+"_"+m],!1,!1));null!=a.l&&xb(a,c)}else null!=a.l&&xb(a,c)}}else null!=a.l&&xb(a,c);1==T.EnableCustomFOUTHandler&&
ob(a,"mti_hide_element")}function xb(a,c){var b="string"==typeof c?document.getElementById(c):c,e=new V(null!=b?c.parentElement:document.body,a.a,a.f.pfL);e.J({});e=e.C;0==e.length&&e.push(b);mti.bind(a.l,a.l.ha,e)()}function qb(a){for(var c=[],b=a.length>>>0;b--;)c[b]=a[b];return c}
function tb(a,c){var b="img script noscript iframe object style param embed link meta head title br hr svg path".split(" "),e=sb(a,c),d,f;e.u&&(d=e.N,f="n4",a.j&&(f=e.fontStyle.charAt(0)+e.fontWeight/100));if(void 0!==c&&null!==c&&""!==c&&c.tagName&&1===c.nodeType&&0>a.a.indexOf(b,c.tagName.toLowerCase())){var h=na(a.a,c),b=!1;""!=h.replace(/\s/g,"")&&e.u&&(500>h.length?(e=h.split("").sort().join(""),eb(a,e,d+"abcde"+(a.j?"_"+f:""),!0)!=a.X[d+"_"+f]&&(b=!0)):b=!0,b&&E(c,"mti_hide_element"));for(c=
c.firstChild;c;)tb(a,c),c=c.nextSibling}}function pb(a){var c,b=a.length,e=!1;for(c=0;c<b;c++)if(-1<a[c].indexOf("mtiSelector")){e=!0;break}return e};function ib(a){a=a.replace(/\s+/g,"%20");a=document.cookie.split(a+"=");var c=null;2==a.length&&(c=a.pop().split(";").shift());return 1==c?!0:!1}
function eb(a,c,b,e){var d="";e&&(a.v?(d=b.substring(b.length-3,b.length),b=b.substring(0,b.length-8)):b=b.substring(0,b.length-5));mb(b,a.w)&&(b=mb(b,a.w).slice(0,-3));b+=d;if("undefined"!==typeof Storage){a:{var f;try{f=window.localStorage.getItem(b)}catch(h){console&&console.log("MTI_webfont_service::localStorage.getItem error::"+h.message);a=!1;break a}a=null==f?!1:f.length>c.length?lb(f,c)?f:!1:!1}if(0==a&&c){a=c;try{var g=window.localStorage.getItem(b);null!=g&&(a+=g);a=ua(a).split("").sort().join("");
window.localStorage.setItem(b,a)}catch(l){console&&console.log("MTI_webfont_service::localStorage.setItem error::"+l.message)}}else if(0<a.length)return a}return c};function ob(a,c){for(var b=pa(a.a,c),e=new RegExp(c,"ig");0<b.length;){for(var d=0;d<b.length;d++)1==b[d].className.split(" ").length?b[d].removeAttribute("class"):b[d].className=b[d].className.replace(e," ").replace(/^\s+|\s+$/g,"");b=pa(a.a,c)}}
mti.o.prototype.M=function(a,c,b,e,d){var f=this.D(a).split(","),h=[];if(b instanceof Array){for(var g in b)b.hasOwnProperty(g)&&h.push(b[g]);if(e){if(d){a:{if("undefined"!=typeof a&&null!=a){if("undefined"!=typeof a.currentStyle){b=a.currentStyle.fontStyle;break a}if(b=this.A.defaultView.getComputedStyle(a,null)){b=b.getPropertyValue("font-style");break a}}b=""}a:{if("undefined"!=typeof a&&null!=a){if("undefined"!=typeof a.currentStyle){e=a.currentStyle.fontWeight;break a}if(e=this.A.defaultView.getComputedStyle(a,
null)){d=e.getPropertyValue("font-weight");e="bold"==d.toLowerCase()?700:"normal"==d.toLowerCase()?400:e.getPropertyValue("font-weight");break a}}e=""}h.push(c+"_"+b.charAt(0)+e/100)}a.style.fontWeight="";a.style.fontStyle=""}for(g in f)f.hasOwnProperty(g)&&h.push(f[g]);h=sa(h);a.style.fontFamily=h;a.setAttribute("data-mtiFont",c)}};
function $a(a,c){if(!0===mti.o.b)c();else{var b=a.a.A;if("MSIE"==a.c.getName()){var e=!1,d=function(){e||(e=!0,c(),mti.o.b=!0)};(function(){try{if("msie"==a.H&&11<=a.version.i?b.documentElement.scrollLeft:b.documentElement.doScroll("left"),"complete"!=b.readyState){setTimeout(arguments.callee,50);return}}catch(c){setTimeout(arguments.callee,50);return}d()})();b.onreadystatechange=function(){"complete"==b.readyState&&(b.onreadystatechange=null,d())}}else"AppleWebKit"==a.c.Ca&&525>a.c.Ba.i?function(){-1<
["loaded","complete"].indexOf(b.readyState)?(c(),mti.o.b=!0):setTimeout(arguments.callee,50)}():b.addEventListener?"loading"==b.readyState?b.addEventListener("DOMContentLoaded",function(){c();mti.o.b=!0},!1):window.addEventListener("load",function(){c();mti.o.b=!0},!1):window.onload=function(){c();mti.o.b=!0}}}
function Za(a,c,b){"complete"==document.readyState?setTimeout(function(){c.apply(a,[a.h,b,!1])},500):document.addEventListener("readystatechange",function(){"complete"==document.readyState&&setTimeout(function(){c.apply(a,[a.h,b,!1])},500)});document.addEventListener?document.addEventListener("keydown",function(b){a.pa.apply(a,[b])}):window.attachEvent?window.attachEvent("onkeydown",function(b){a.pa.apply(a,[b])}):document.addEventListener("keydown",function(b){a.pa.apply(a,[b])})};
})(this,document);