;(function(window,document,undefined){var B,aa=aa||{};function ca(a,c,b){return a.call.apply(a.bind,arguments)}function da(a,c,b){if(!a)throw Error();if(2<arguments.length){var f=Array.prototype.slice.call(arguments,2);return function(){var b=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(b,f);return a.apply(c,b)}}return function(){return a.apply(c,arguments)}}function ea(a,c,b){ea=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ca:da;return ea.apply(null,arguments)}
var fa=aa.ab&&Date.now||function(){return+new Date};mti={bind:function(a,c,b){var f=2<arguments.length?Array.prototype.slice.call(arguments,2):[];return function(){f.push.apply(f,arguments);return c.apply(a,f)}}};var ga={};function ha(a,c){this.g=c||a;this.D=this.g.document;this.b=void 0}B=ha.prototype;B.createElement=function(a,c,b){a=this.D.createElement(a);if(c)for(var f in c)c.hasOwnProperty(f)&&("style"==f?ia(this,a,c[f]):a.setAttribute(f,c[f]));b&&a.appendChild(this.D.createTextNode(b));return a};function D(a,c,b){a=a.D.getElementsByTagName(c)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(b,a.lastChild)}B.Fa=function(a){function c(){b.D.body?a():setTimeout(c,0)}var b=this;c()};
function ja(a){a.parentNode&&a.parentNode.removeChild(a)}function H(a,c){if(!("undefined"!==typeof SVGElement&&a instanceof SVGElement)){for(var b=a.className.split(/\s+/),f=0,d=b.length;f<d;f++)if(b[f]==c)return;b.push(c);a.className=b.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}}
function ka(a,c){if(!("undefined"!==typeof SVGElement&&a instanceof SVGElement)){for(var b=a.className.split(/\s+/),f=[],d=0,e=b.length;d<e;d++)b[d]!=c&&f.push(b[d]);a.className=f.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}}function na(a,c){if("undefined"!==typeof SVGElement&&a instanceof SVGElement)return!1;for(var b=a.className.split(/\s+/),f=0,d=b.length;f<d;f++)if(b[f]==c)return!0;return!1}
function ia(a,c,b){if(void 0===a.b){var f=a.D.createElement("p");f.innerHTML='<a style="top:1px;">w</a>';a.b=/top/.test(f.getElementsByTagName("a")[0].getAttribute("style"))}a.b?c.setAttribute("style",b):c.style.cssText=b}
B.getComputedStyle=function(a){if("undefined"!=typeof a&&null!=a){if(1!=a.nodeType)return"";var c={};if("undefined"!=typeof a.currentStyle&&null!=a.currentStyle)return c.fontFamily=a.currentStyle.fontFamily,c.fontWeight="normal"==a.currentStyle.fontWeight?400:"bold"==a.currentStyle.fontWeight?700:a.currentStyle.fontWeight,c.fontStyle=a.currentStyle.fontStyle,c;a=this.D.defaultView.getComputedStyle(a,null);if("undefined"!=typeof a&&null!=a)return c.fontFamily=a.getPropertyValue("font-family"),c.fontWeight=
"normal"==a.getPropertyValue("font-weight")?400:"bold"==a.getPropertyValue("font-weight")?700:a.getPropertyValue("font-weight"),c.fontStyle=a.getPropertyValue("font-style"),c}return""};B.B=function(a){if("undefined"!=typeof a&&null!=a){if("undefined"!=typeof a.currentStyle)return a.currentStyle.fontFamily;if(a=this.D.defaultView.getComputedStyle(a,null))return a.getPropertyValue("font-family")}return""};
function oa(a,c){if("undefined"!=typeof c&&null!=c){if("undefined"!=typeof c.currentStyle)return c.currentStyle.fontWeight;var b=a.D.defaultView.getComputedStyle(c,null);if(b){var f=b.getPropertyValue("font-weight");return"bold"==f.toLowerCase()?700:"normal"==f.toLowerCase()?400:b.getPropertyValue("font-weight")}}return""}
function pa(a,c){if("undefined"!=typeof c&&null!=c){if("undefined"!=typeof c.currentStyle)return c.currentStyle.fontStyle;var b=a.D.defaultView.getComputedStyle(c,null);if(b)return b.getPropertyValue("font-style")}return""}
function qa(a,c){var b="";if(void 0!=typeof c&&null!=c){void 0!=c&&null!=c&&"INPUT"==c.tagName&&(b+=c.value);c=c.childNodes||c;for(var f="img script noscript iframe object style param embed link meta head title br hr svg path".split(" "),d=0;d<c.length;d++)if(8!=c[d].nodeType&&0>a.indexOf(f,c[d].tagName?c[d].tagName.toLowerCase():"")){var e;e=(e=c[d].parentNode)?"undefined"!=typeof e.currentStyle?e.currentStyle.textTransform:(e=a.D.defaultView.getComputedStyle(e,null))?e.getPropertyValue("text-transform"):
"":void 0;if("none"!=e)e=1!=c[d].nodeType?c[d].nodeValue.replace(/(?:\r\n|\r|\n)/g," "):"",b+=e.toLowerCase()+e.toUpperCase();else{if("none"!=ra(a,c[d].parentNode)){var g=c[d].parentNode;e=ra(a,c[d].parentNode);if("undefined"!=typeof g){for(var h=g.childNodes,l=g=0;l<h.length;l++)1==h[l].nodeType&&g++;h="";switch(e){case "upper-alpha":h="ABCDEFGHIJKLMNOPQRSTUVWXYZ".substring(0,g);break;case "lower-latin":h="abcdefghijklmnopqrstuvwxyz".substring(0,g);break;case "decimal":h="1234567890".substring(0,
g);break;case "decimal-leading-zero":h="0"+"1234567890".substring(0,g);break;case "lower-roman":h="ivxlcdm";break;case "upper-roman":h="IVXLCDM";break;default:h=""}}b=b+h}b+=1!=c[d].nodeType?c[d].nodeValue.replace(/(?:\r\n|\r|\n)/g," "):""}}return b}}B.getElementById=function(a){return this.D.getElementById(a)};
function sa(a,c){if(document.getElementsByClassName)return document.getElementsByClassName(c);var b=[];ua(a.a,document.body,function(a){var d;d=a.className;var e;if(d)for(d=d.split(" "),e=0;e<d.length;e++)if(d[e]===c){b.push(a);break}});return b}
B.H=function(a,c,b,f,d){var e=[],g=this.B(a).split(","),h="",l="",k;a:if(k=!1,g instanceof Array)for(var m=0;m<g.length;m++)if(b instanceof Array)for(var r=0;r<b.length;r++){if(J(g[m])==J(b[r])){k=!0;break a}}else{if(J(g[m])==J(b)){k=!0;break}}else if(b instanceof Array)for(m=0;m<b.length;m++)if(g==b[m]){k=!0;break}if(k)return null;if(b instanceof Array)for(h=0;h<g.length;h++)if(J(g[h])!=c)if(-1<J(g[h]).indexOf(c))for(l=0;l<b.length;l++)""!=b[l]&&(e.push(b[l]),e.push(c));else e.push(g[h]);else if(b instanceof
Array)for(l=0;l<b.length;l++)""!=b[l]&&(f?d?(k=pa(this,a),m=oa(this,a),r=J(b[l])+"_"+k.charAt(0)+m/100,e.push(r)):e.push(b[l]):e.push(b[l]),e.push(c));else e.push(b),e.push(c);else if(f)d?(k=pa(this,a),m=oa(this,a),d=J(this.B(a)),r=c+"_"+k.charAt(0)+m/100,J(b),b=r.length,b=r.slice(b-2,b),h=100*b.charAt(1),l=b.charAt(0),c==d&&k.charAt(0)==l&&m==h&&(e.push(r),e.push(c))):(e.push(b),e.push(c));else for(h=0;h<g.length;h++)if(J(g[h])!=c)0==J(g[h]).indexOf(c)?""!=b&&(e.push(b),e.push(c)):(e.push(g[h]),
e.push(c));else if(b instanceof Array)for(l=0;l<b.length;l++)""!=b[l]&&(f?d?(k=pa(this,a),m=oa(this,a),r=J(b[l])+"_"+k.charAt(0)+m/100,e.push(r)):e.push(b[l]):e.push(b[l]),e.push(c));else e.push(b),e.push(c);e=va(e);if(0<e.length&&e[0]!=c){b="";for(h=0;h<e.length;h++)b+="'"+e[h]+"'",h!=e.length-1&&(b+=",");b+="";a.setAttribute("data-mtiFont",c);if(f)return a.style.fontWeight="",a.style.fontStyle="",a.style.fontFamily=""+b,a.style.fontFamily;c=""+b;a.style.setProperty?a.style.setProperty("font-family",
""):a.style.setAttribute("font-family","");a.setAttribute("style",a.style.cssText+"font-family:"+c+" !important;")}else return null};function wa(a,c){for(var b=c.parentNode;null!=b;){if(b==a)return!0;b=b.parentNode}return!1}function ua(a,c,b){b(c);for(c=c.firstChild;c;)ua(a,c,b),c=c.nextSibling}B.indexOf=function(a,c){if(a){if(a.indexOf)return a.indexOf(c);for(var b=0;b<a.length;b++)if(a[b]==c)return b}return-1};
function J(a){return a.replace(/^\s|\s$/g,"").replace(/'|"/g,"").replace(/,\s*/g,"|")}function va(a){for(var c={},b=[],f=0,d=a.length;f<d;++f)c.hasOwnProperty(J(a[f]))||(b.push(J(a[f])),c[J(a[f])]=1);return b}B.B=function(a){if("undefined"!=typeof a&&null!=a){if("undefined"!=typeof a.currentStyle)return a.currentStyle.fontFamily;if(a=this.D.defaultView.getComputedStyle(a,null))return a.getPropertyValue("font-family")}return""};
function xa(a){if(a&&"string"==typeof a){for(var c="",b=a.length,f=null,d=0;d<b;d++)f=a.charAt(d),-1==c.indexOf(f)&&(c+=f);return c}return""}function ra(a,c){if(c){if("undefined"!=typeof c.currentStyle)return c.currentStyle["list-style-type"];var b=a.D.defaultView.getComputedStyle(c,null);return b?b.getPropertyValue("list-style-type"):""}};function L(a,c){this.g=a;this.b=c};function N(a,c,b,f){this.j=null!=a?a:null;this.J=null!=c?c:null;this.b=null!=b?b:null;this.g=null!=f?f:null}var ya=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/;N.prototype.toString=function(){return[this.j,this.J||"",this.b||"",this.g||""].join("")};
function O(a){a=ya.exec(a);var c=null,b=null,f=null,d=null;a&&(null!==a[1]&&a[1]&&(c=parseInt(a[1],10)),null!==a[2]&&a[2]&&(b=parseInt(a[2],10)),null!==a[3]&&a[3]&&(f=parseInt(a[3],10)),null!==a[4]&&a[4]&&(/^[0-9]+$/.test(a[4])?d=parseInt(a[4],10):d=a[4]));return new N(c,b,f,d)};function P(a,c,b,f,d,e,g,h){this.T=a;this.oa=c;this.Ha=b;this.Ga=f;this.la=d;this.Oa=e;this.b=h}P.prototype.getName=function(){return this.T};function za(){this.c=navigator.userAgent}var Aa=new P("Unknown",new N,"Unknown",new N,"Unknown",new N,0,new L(!1,!1));
function Ba(){var a=new za;if(-1!=a.c.indexOf("MSIE")||-1!=a.c.indexOf("Trident/")){var c=Ca(a),b=O(Da(a)),f=null,d=null,e=null,e=Q(a.c,/Trident\/([\d\w\.]+)/,1),f=-1!=a.c.indexOf("MSIE")?O(Q(a.c,/MSIE ([\d\w\.]+)/,1)):O(Q(a.c,/rv:([\d\w\.]+)/,1));""!=e?(d="Trident",e=O(e)):(d="Unknown",e=new N);a=new P("MSIE",f,d,e,c,b,0,new L("Windows"==c&&6<=f.j||"Windows Phone"==c&&8<=b.j,!1))}else if(-1!=a.c.indexOf("Opera"))a:if(c="Unknown",b=O(Q(a.c,/Presto\/([\d\w\.]+)/,1)),f=O(Da(a)),null!==b.j?c="Presto":
(-1!=a.c.indexOf("Gecko")&&(c="Gecko"),b=O(Q(a.c,/rv:([^\)]+)/,1))),-1!=a.c.indexOf("http://fast.fonts.net/jsapi/Opera Mini/"))d=O(Q(a.c,/Opera Mini\/([\d\.]+)/,1)),a=new P("OperaMini",d,c,b,Ca(a),f,0,new L(!1,!1));else{if(-1!=a.c.indexOf("http://fast.fonts.net/jsapi/Version/")&&(d=O(Q(a.c,/Version\/([\d\.]+)/,1)),null!==d.j)){a=new P("Opera",d,c,b,Ca(a),f,0,new L(10<=d.j,!1));break a}d=O(Q(a.c,/Opera[\/ ]([\d\.]+)/,1));a=null!==d.j?new P("Opera",d,c,b,Ca(a),f,0,new L(10<=d.j,!1)):new P("Opera",new N,c,b,Ca(a),f,0,new L(!1,!1))}else/OPR\/[\d.]+/.test(a.c)?
a=Ea(a):/AppleWeb(K|k)it/.test(a.c)?a=Ea(a):-1!=a.c.indexOf("Gecko")?(c="Unknown",b=new N,f=O(Da(a)),d=!1,-1!=a.c.indexOf("Firefox")?(c="Firefox",b=O(Q(a.c,/Firefox\/([\d\w\.]+)/,1)),d=3<=b.j&&5<=b.J):-1!=a.c.indexOf("Mozilla")&&(c="Mozilla"),e=O(Q(a.c,/rv:([^\)]+)/,1)),d||(d=1<e.j||1==e.j&&9<e.J||1==e.j&&9==e.J&&2<=e.b),a=new P(c,b,"Gecko",e,Ca(a),f,0,new L(d,!1))):a=Aa;return a}
function Ca(a){var c=Q(a.c,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=c)return/BB\d{2}/.test(c)&&(c="BlackBerry"),c;a=Q(a.c,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS|PlayStation|CrKey)/,1);return""!=a?("Mac_PowerPC"==a?a="Macintosh":"PlayStation"==a&&(a="Linux"),a):"Unknown"}
function Da(a){var c=Q(a.c,/Windows Phone( OS)? ([^;)]+)/,2);if(c||(c=Q(a.c,/(OS X|Windows NT|Android) ([^;)]+)/,2))||(c=Q(a.c,/(iPhone )?OS ([\d_]+)/,2)))return c;if(c=Q(a.c,/(?:Linux|CrOS|CrKey) ([^;)]+)/,1))for(var c=c.split(/\s/),b=0;b<c.length;b+=1)if(/^[\d\._]+$/.test(c[b]))return c[b];return(a=Q(a.c,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function Ea(a){var c=Ca(a),b=O(Da(a)),f=O(Q(a.c,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,1)),d="Unknown",e=new N,e="Unknown",g=!1;/OPR\/[\d.]+/.test(a.c)?d="Opera":-1!=a.c.indexOf("Edge")?d="Edge":-1!=a.c.indexOf("Chrome")||-1!=a.c.indexOf("CrMo")||-1!=a.c.indexOf("CriOS")?d="Chrome":/Silk\/\d/.test(a.c)?d="Silk":"BlackBerry"==c||"Android"==c?d="BuiltinBrowser":-1!=a.c.indexOf("PhantomJS")?d="PhantomJS":-1!=a.c.indexOf("Safari")?d="Safari":-1!=a.c.indexOf("AdobeAIR")?d="AdobeAIR":-1!=a.c.indexOf("PlayStation")?
d="BuiltinBrowser":-1!=a.c.indexOf("FBAN")&&(d="FBWebUI");"BuiltinBrowser"==d?e="Unknown":"Silk"==d?e=Q(a.c,/Silk\/([\d\._]+)/,1):"Chrome"==d?e=Q(a.c,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):-1!=a.c.indexOf("http://fast.fonts.net/jsapi/Version/")?e=Q(a.c,/Version\/([\d\.\w]+)/,1):"AdobeAIR"==d?e=Q(a.c,/AdobeAIR\/([\d\.]+)/,1):"Opera"==d?e=Q(a.c,/OPR\/([\d.]+)/,1):"PhantomJS"==d?e=Q(a.c,/PhantomJS\/([\d.]+)/,1):"FBWebUI"==d?e=Q(a.c,/FBSV\/([\d.]+)/,1):"Edge"==d&&(e=Q(a.c,/Edge\/([\d.]+)/,1));e=O(e);g="AdobeAIR"==d?2<e.j||2==e.j&&
5<=e.J:"BlackBerry"==c?10<=b.j:"Android"==c?2<b.j||2==b.j&&1<b.J:526<=f.j||525<=f.j&&13<=f.J;return new P(d,e,"AppleWebKit",f,c,b,0,new L(g,536>f.j||536==f.j&&11>f.J))}function Q(a,c,b){return(a=a.match(c))&&a[b]?a[b]:""};function Fa(a){this.g=a||"-"}Fa.prototype.b=function(a){for(var c=[],b=0;b<arguments.length;b++)c.push(arguments[b].replace(/[\W_]+/g,"").toLowerCase());return c.join(this.g)};function Ga(a,c,b){this.a=a;this.g=c;this.u=b;this.b=new Fa("-")}function Ha(a){H(a.g,a.b.b("mti","loading"));Ia(a,"loading")}function Ja(a){ka(a.g,a.b.b("mti","loading"));na(a.g,a.b.b("mti","active"))||H(a.g,a.b.b("mti","inactive"));Ia(a,"inactive")}function Ia(a,c,b){if(a.u[c])if(b)a.u[c](b.getName(),R(b));else a.u[c]()};function S(a,c){this.T=a;this.Z=4;this.W="n";var b=(c||"n4").match(/^([nio])([1-9])$/i);b&&(this.W=b[1],this.Z=parseInt(b[2],10))}S.prototype.getName=function(){return this.T};S.prototype.Ea=function(a){var c=[];a=a.split(/,\s*/);for(var b=0;b<a.length;b++){var f=a[b].replace(/['"]/g,"");-1==f.indexOf(" ")?c.push(f):c.push("'"+f+"'")}return c.join(",")};function R(a){return a.W+a.Z};function Ka(a,c){this.a=a;this.g=c;this.b=this.a.createElement("span",{"aria-hidden":"true"},this.g)}function La(a){D(a.a,"body",a.b)}function Ma(a){var c="position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+a.Ea(a.T)+"!important;",b="normal",f=a.Z+"00";"o"===a.W?b="oblique":"i"===a.W&&(b="italic");return c+("font-style:"+b+";font-weight:"+f+";")};function Na(a,c,b,f,d,e,g,h){this.fa=a;this.Ka=c;this.a=b;this.b=f;this.aa=h||"BESb\uc5d0swy";this.ja=d;this.L={};this.Na=e||5E4;this.ha=g||null;this.u=this.g=null;a=new Ka(this.a,this.aa);La(a);for(var l in T)T.hasOwnProperty(l)&&(c=new S(T[l],R(this.b)),ia(a.a,a.b,Ma(c)),this.L[T[l]]=a.b.offsetWidth);ja(a.b)}var T={$a:"serif",Za:"sans-serif",Wa:"monospace"};function Oa(a,c,b){for(var f in T)if(T.hasOwnProperty(f)&&c===a.L[T[f]]&&b===a.L[T[f]])return!0;return!1}
function Pa(a){var c=a.g.b.offsetWidth,b=a.u.b.offsetWidth;c===a.L.serif&&b===a.L["sans-serif"]||a.ja.b&&Oa(a,c,b)?fa()-a.La>=a.Na?a.ja.b&&Oa(a,c,b)&&(null===a.ha||a.ha.hasOwnProperty(a.b.getName()))?Qa(a,a.fa):Qa(a,a.Ka):Ra(a):Qa(a,a.fa)}function Ra(a){setTimeout(ea(function(){Pa(this)},a),25)}function Qa(a,c){ja(a.g.b);ja(a.u.b);c(a.b)};function Sa(a,c,b,f){this.a=c;this.b=b;this.g=0;this.L=this.u=!1;this.ja=f;this.ha=a.b}
function Ta(a,c,b,f,d){if(0===c.length&&d)Ja(a.b);else for(a.g+=c.length,d&&(a.u=d),d=0;d<c.length;d++){var e=c[d],g=b[e.getName()],h=a.b,l=e;H(h.g,h.b.b("mti",l.getName(),R(l).toString(),"loading"));Ia(h,"fontloading",l);e=new Na(ea(a.aa,a),ea(a.fa,a),a.a,e,a.ha,a.ja,f,g);e.g=new Ka(e.a,e.aa);La(e.g);e.u=new Ka(e.a,e.aa);La(e.u);e.La=fa();g=e.g;h=new S(e.b.getName()+",serif",R(e.b));ia(g.a,g.b,Ma(h));g=e.u;h=new S(e.b.getName()+",sans-serif",R(e.b));ia(g.a,g.b,Ma(h));Pa(e)}}
Sa.prototype.aa=function(a){var c=this.b;ka(c.g,c.b.b("mti",a.getName(),R(a).toString(),"loading"));ka(c.g,c.b.b("mti",a.getName(),R(a).toString(),"inactive"));H(c.g,c.b.b("mti",a.getName(),R(a).toString(),"active"));Ia(c,"fontactive",a);this.L=!0;Ua(this)};Sa.prototype.fa=function(a){var c=this.b;ka(c.g,c.b.b("mti",a.getName(),R(a).toString(),"loading"));na(c.g,c.b.b("mti",a.getName(),R(a).toString(),"active"))||H(c.g,c.b.b("mti",a.getName(),R(a).toString(),"inactive"));Ia(c,"fontinactive",a);Ua(this)};
function Ua(a){0==--a.g&&a.u&&(a.L?(a=a.b,ka(a.g,a.b.b("mti","loading")),ka(a.g,a.b.b("mti","inactive")),H(a.g,a.b.b("mti","active")),Ia(a,"active")):Ja(a.b))};mti.Ua=function(){this.Ea='"'};mti.I=function(){this.ma=mti.I.g;this.N=mti.I.u};mti.I.g=["font-style","font-weight"];mti.I.u={"font-style":[["n","normal"]],"font-weight":[["4","normal"]]};mti.I.b=function(a,c,b){this.Ba=a;this.Qa=c;this.N=b};mti.I.b.prototype.compact=function(a,c){for(var b=0;b<this.N.length;b++)if(c==this.N[b][1]){a[this.Ba]=this.N[b][0];break}};mti.I.b.prototype.expand=function(a,c){for(var b=0;b<this.N.length;b++)if(c==this.N[b][0]){a[this.Ba]=this.Qa+":"+this.N[b][1];break}};
mti.I.prototype.compact=function(a){var c=["n","4"];a=a.split(";");for(var b=0,f=a.length;b<f;b++){var d=a[b].replace(/\s+/g,"").split(":");if(2==d.length){var e=d[1];a:{for(var d=d[0],g=0;g<this.ma.length;g++)if(d==this.ma[g]){d=new mti.I.b(g,d,this.N[d]);break a}d=null}d&&d.compact(c,e)}}return c.join("")};
mti.I.prototype.expand=function(a){if(2!=a.length)return null;for(var c=[null,null],b=0,f=this.ma.length;b<f;b++){var d=this.ma[b];(new mti.I.b(b,d,this.N[d])).expand(c,a.substr(b,1))}return c[0]&&c[1]?c.join(";")+";":null};function Va(a,c,b){this.u=a;this.ya=c;this.c=b;this.b=this.g=0}Va.prototype.load=function(a){var c=a.context||this.u;this.a=new ha(this.u,c);c=new Ga(this.a,c.document.documentElement,a);if(this.c.b.g){var b=this.ya,f=this.a,d=[],e;for(e in a)if(a.hasOwnProperty(e)){var g=b.b[e];g&&d.push(g(a[e],f))}a=a.timeout;this.b=this.g=d.length;a=new Sa(this.c,this.a,c,a);e=0;for(b=d.length;e<b;e++)f=d[e],f.Ta(this.c,ea(this.L,this,f,c,a))}else Ja(c)};
Va.prototype.L=function(a,c,b,f){var d=this;f?a.load(function(a,f,h){Wa(d,c,b,a,f,h)}):(a=0==--this.g,this.b--,a&&(0==this.b?Ja(c):Ha(c)),Ta(b,[],{},null,a))};function Wa(a,c,b,f,d,e){var g=0==--a.g;g&&Ha(c);setTimeout(function(){Ta(b,f,d||{},e||null,g)},0)};var Xa=window,Ya=Ba(),Za=Xa.MonoTypeWebFonts=new Va(window,new function(){this.b={}},Ya);window.MonoTypeWebFonts.load=Za.load;mti.va=4E4;
mti.s=function(a,c,b,f,d){this.P=a;this.c=c;this.a=b;this.f=f;this.Ia={};this.l=d;this.h=[];this.w=f.efg;this.o={};this.i=f.efg;this.P.mti_element_cache=[];this.ga=[];this.na=[];this.G=[];this.$={};this.O=[];this.V=[];this.pa=0;this.A=[];this.version=this.K=void 0;this.ra=this.m=!1;this.xa={TTF:"truetype",WOFF:"woff",SVG:"svg",MTX:"truetype",OTF:"opentype",WOFF2:"woff2"};this.C={};this.Da=0;this.S=!1;1==U.UseTextIndent?this.ca="text-align:left;text-indent:-9999px;font-size:0px":this.ca="visibility:hidden;";
this.ea=this.f.reqSub||(void 0!==U.EnableDSForAllFonts?U.EnableDSForAllFonts:!1);this.K=a=this.c.getName().toLowerCase();this.version=this.c.oa;this.m="msie"===a&&8>=this.version.j?!0:!1;this.ra="msie"==a&&8>this.version.j?!0:!1;this.S="msie"==a?!0:!1;this.qa={EOT:2,SVG:11,OTF:13,TTF:1,WOFF:3,WOFF2:14}};mti.s.g="monotype";mti.s.b=!1;mti.s.prototype={Ta:function(a,c){var b=this,f=b.f.projectId,d;if(f){b.P.mti_element_cache=[];$a(b);if(null!==b.l&&!1===b.ea)if(setTimeout(function(){document.documentElement.style.visibility=""},300),void 0!==U.PreLoadFonts&&b.isArray(U.PreLoadFonts)){var e=U.PreLoadFonts;d=[];for(var g=0;g<e.length;g++){var h=e[g].split(":"),l=h[0],h=1<h.length?h[1].split(","):"n4",k="n4";if(b.isArray(h)&&0<h.length)for(var m=0;m<h.length;m++)k=h[m],k=b.Aa(l,k),void 0!==k&&d.push(k);else k=b.Aa(l,k),void 0!==k&&
d.push(k)}ab(b,d,"","",!0);c(!0)}else b.da.call(b,!0,!0,!0),void 0===U.LoadAllFonts&&void 0===U.EnableCustomFOUTHandler||c(U.LoadAllFonts||U.EnableCustomFOUTHandler),this.m||b.sa();else U.UseHybrid&&(setTimeout(function(){document.documentElement.style.visibility=""},700),U.EnableCustomFOUTHandler=!0,b.Y(b.f.pfL,!1,!0)),d=function(){U.UseHybrid&&(window.MonoTypeWebFonts.addEvent("active",function(){bb(b,b.Y,!1)}),window.MonoTypeWebFonts.addEvent("inactive",function(){bb(b,b.Y,!1)}));this.m||b.sa();
b.ea?b.da.call(b):b.da.call(b,!0);c(U.EnableCustomFOUTHandler)},setTimeout(function(){document.documentElement.style.visibility=""},750),!0===U.isAsync?U.onReady=d:(b.ea?cb(b,d):this.Fa(function(){b.da.call(b,!0);c(U.EnableCustomFOUTHandler)}),this.m||!b.f.enableOtf||b.ea||cb(b,b.sa.bind(b)));d=null;"function"===typeof b.P["__MonotypeConfiguration__"+f]&&(d=b.P["__MonotypeConfiguration__"+f]());if(void 0!==d||null!==d)loadAllFonts=d.loadAllFonts;var r=function(){var a=[];if(loadAllFonts)for(var c=
0;c<b.f.pfL.length;c++){var d,e,g,h=b.f.pfL[c].fontfamily;void 0!=b.f.pfL[c].fontWeight&&void 0!=b.f.pfL[c].fontStyle&&(g=b.f.pfL[c].fontStyle,e=b.f.pfL[c].fontWeight,d=g.charAt(0)+e/100,b.m&&(h=h+"_"+g.charAt(0)+e/100,e="400",g="normal",d="n4"));var l=new S(h,d);l.fontfamily=h;l.fontWeight=e;l.fontStyle=g;a.push(l)}if(0<b.h.length||0<a.length){var k=[];b.h&&(k=b.h);loadAllFonts&&(k=a);b.P["__mti_fntLst"+f]=function(){for(var a=[],b=[],c=0;c<k.length;c++)a.push({fontfamily:k[c].T,fontStyle:k[c].W,
fontWeight:k[c].Z}),b.push(k[c]);return a}}else setTimeout(function(){r()},0)};r()}else c(U.EnableCustomFOUTHandler)},da:function(a,c){a=this;var b=!1,f={},d={};U.UseHybrid&&0<a.pa?a.O.length!=a.pa&&(b=!0):b=!0;if(b||null!=a.l){var d=new V(document.body,a.a,a.f.pfL),e=d.M(document.body),f=d.ba(),d=d.F;null!=a.l&&mti.bind(a.l,a.l.load,d)();if(c)"";else for(var b=a,g=d,h=0;h<g.length;h++)for(var l in b.o)-1<b.a.B(g[h]).indexOf(l)&&(void 0==g[h].getAttribute("id"),b.a.H(g[h],l,b.o[l],b.m,b.w))}l=[];
for(b=0;b<a.f.pfL.length;b++){var g=a.f.pfL[b],k,m,r,h=g.enableSubsetting,z=g.enableOtf,t=g.contentIds,w=g.subsetOption;if(!g.enableSubsetting){void 0!=g.fontWeight&&void 0!=g.fontStyle&&(m=g.fontWeight,r=g.fontStyle,k=r.charAt(0)+m/100);var y=new S(g.fontfamily,k);y.fontfamily=g.fontfamily;y.fontWeight=void 0!=g.fontWeight?m:"4";y.fontStyle=void 0!=g.fontStyle?r:"n";y.enableSubsetting=h;y.contentIds=t;y.enableOtf=z;y.subsetOption=w;l.push(y)}}k=l;m=null==k?0:k.length;r={};b=[];for(l=0;l<m;l+=1)r[k[l].T+
"||"+k[l].Z+"||"+k[l].W]=k[l];for(l in r)b.push(r[l]);l=b;ab(a,f,e,"",!0);ab(a,l,e,"",!1);a.P.mti_element_cache=d},Aa:function(a,c){for(var b=0;b<this.f.pfL.length;b++){var f=this.f.pfL[b],d,e,g;void 0!=f.fontWeight&&void 0!=f.fontStyle&&(e=f.fontWeight,g=f.fontStyle,d=g.charAt(0)+e/100);if(f.fontfamily==a&&(this.i?c==d:1)){var b=f.enableSubsetting,h=f.enableOtf,l=f.contentIds,k=f.subsetOption,m=f.variationId,r=f.otfJsContentId;d=new S(f.fontfamily,d);d.fontfamily=f.fontfamily;d.fontWeight=void 0!=
f.fontWeight?e:"4";d.fontStyle=void 0!=f.fontStyle?g:"n";d.enableSubsetting=b;d.contentIds=l;d.enableOtf=h;d.subsetOption=k;d.variationId=m;d.otfJsContentId=r;return d}}}};MonoTypeWebFonts.ya.b[mti.s.g]=function(a){var c=Ba(),b=new ha(window),f=null;a.enableOtf&&(f=new mti.Xa(b,c,a));c=new mti.s(window,c,b,a,f);if(a.reqSub||U.EnableDSForAllFonts||a.enableOtf){var d=new mti.wa(c);window.MonoTypeWebFonts.renderPartial=function(a,b){d.Ra(a,b)}}return c};
var db={ec:"true",dfcURL:"http://api2.fonts.com/FontSubsetter.ashx",fontdataversion:"v2",sO:"true",ffArray:{safari:{"3.1":"ttf","5.1":"woff"},msafari:{1:"svg","4.2":"ttf","5.1":"woff"},chrome:{3:"svg",4:"ttf",5:"woff",36:"woff2"},opera:{10:"ttf","11.10":"woff","26.0":"woff2"},msie:{4:"eot",9:"woff"},mozilla:{"3.5":"ttf","3.6":"woff","39.0":"woff2"},edge:{12:"woff",14:"woff2"}},bsmcArray:{safari:{"3.1":"2000","5.1":"15600"},msafari:{1:"15600"},chrome:{3:"15600"},opera:{10:"15600"},msie:{4:"1000",9:"2080"},
mozilla:{"3.5":"15600"},edge:{12:"15600"}},fctypeArray:{ttf:"1",eot:"2",woff:"3",svg:"11",otf:"13",woff2:"14"},specialChar:"%u201C %u201D %u2200 %u2202 %u2203 %u2205 %u2207 %u2208 %u2209 %u220B %u220F %u2211 %u2018 %u2019 %B0 %u2026 %u2122 %A9 %AE %u2014 %u2013 %A7 %B1 %B7 %u2032 %u2033 %u20AC %u2248 %u2260 %u2264 %u2265 %u221A %u221D %u2220 %u2225 %u2227 %u2228 %u2229 %u222A %u222B %u222E %u2234 %u2235 %u2236 %u2237 %u223D %u224C %u2261 %u226E %u226F %u2299 %u22A5 %u0391 %u0392 %u0393 %u0394 %u0395 %u0396 %u0397 %u0398 %u0399 %u039A %u039B %u039C %u039D %u039E %u039F %u03A0 %u03A1 %u03A3 %u03A4 %u03A5 %u03A6 %u03A7 %u03A8 %u03A9 %u221E %u2190 %u2191 %u2192 %u2193 %u2640 %u2642 + %22 %5C %23 %26 %3F %B7 %3B %3A".split(" ")};
function W(a,c){return void 0!=db[c]?db[c]:a.f[c]};function ab(a,c,b,f,d){var e,g="TTF",h=a.f.projectId,l=W(a,"ec"),k=a.f.fcURL,m=W(a,"dfcURL"),r=document.getElementById("mti_fontface_"+a.f.projectId);a.m&&(r=a.a.createElement("style",{type:"text/css",id:"mti_fontface_"+a.f.projectId}));null==r&&(r=a.a.createElement("style",{type:"text/css",id:"mti_fontface_"+a.f.projectId}));var z="",t=!1,w={},y={};a.o={};var n=null,x=null;void 0!=U.CustomDfcURL&&(m=U.CustomDfcURL);c||(c=[]);!a.m&&a.S&&0<a.A.length&&(z=eb(a,z));for(var q=0;q<c.length;q++){var u=
c[q],v=c[q].fontfamily,p=c[q].contentIds,E=c[q].enableOtf,A=u.subsetOption;e=null;a.i&&(n=c[q].fontWeight,x=c[q].fontStyle,e=x.charAt(0)+n/100,a.w=!0);d&&(null==e?new S(v):new S(v,e),a.h.push(c[q]));26<v.length&&!a.C&&(a.C[v+"_"+(null==e?"n4":e)]="mtiFont"+a.Da++);var g=a.X(p),F="";a.i?F=v+"_"+x.charAt(0)+n/100:F=v+"_n4";u=1==U.EnableDSForAllFonts?!0:u.enableSubsetting;var C=a,M=v,G=n,I=x,y=f,K=C.c.getName(),K=K.toLowerCase();e=C.c.oa;"mozilla"==K.toLowerCase()&&"Unknown"==e&&(K="msie");e="?";l&&
(e+=a.f.ck+"&");e+="fctypeId="+W(C,"fctypeArray")[g]+"&fcId="+p.TTF;e+="&projectId="+h;e+="&content=";var ta="";if(b){var la=null,ma=fb(b,M,G,I);ma?"":ma="";var Z=ma.split("::"),ma=Z[0],Z=Z[1],M=M+(y?y:"");C.w&&(M+="_"+I.charAt(0)+G/100);G=ma.split("").sort().join("");G=hb(C,G,M,y);la="";ma&&(la=G.replace('"',"").replace("?","").replace(";","").replace("#","").replace("&",""));if(la&&0<la.length||Z&&0<Z.length)ta+=("msie"==K?la||"":(la||""))+"BESb\uc5d0swyMm",void 0!==Z&&""!=Z&&
(ta+=Z)}y=e+ta;K=W(C,"bsmcArray");G=C.K;"firefox"==G&&(G="mozilla");/ipad|ipod|iphone/.test(C.c.la.toLowerCase())&&(C.K="msafari");C=C.version.j;K=K[G];G="";I=void 0;for(I in K)parseFloat(C)>=parseFloat(I)&&(G=K[I]);C=G;e=y.length>C?Math.ceil(y.length/(C-e.length)):1;K=e;e=!1;a.ra&&1<K&&(K=1,e=!0,u=!1);C="";if(1<K||f){if(null!==b){t=!0;w[F]||(w[F]=[]);if(b)var gb=b[F];if(gb){y=[];G="";e="n4";a.i&&(e=x.charAt(0)+n/100);I=G=(a.C[v+"_"+e]?a.C[v+"_"+e]:v)+(f?f:"");I+="_"+e;w[F].push(I);b[I]=gb;if(C=1<
K?ib(a,p,h,!1,k,m,a.f.ck,G,n,x,b,g,E,f):ib(a,p,h,u,k,m,a.f.ck,G,n,x,b,g,E,f,A))E="",a.m&&void 0!=x&&void 0!=n?E=I:E=G,z=jb(a,E,"",z,n,x,E,C,g,p,!0,"",!1,!0,f,ba,!1),a.m&&a.i&&!f&&(G+="_"+x.charAt(0)+n/100),y.push("'"+G+"'"),a.V[v+"_"+e]=G;a.o[v+(a.i?"_"+e:"")]=y;!a.m&&a.S&&a.A.push({font:v,url:C,ieFix:ba,fontWeight:n,fontStyle:x,contentIdArray:p,isAjax:f,fFormat:g})}else a.m&&!u&&(a.m&&a.i&&(v+="_"+x.charAt(0)+n/100),C=ib(a,p,h,u,k,m,a.f.ck,v+(f?f:""),n,x,e?null:b,g,E,f,A))&&(z=jb(a,v,"",z,n,x,v,
C,g,p,!0,"",!1,!0,f,ba,!1),!a.m&&a.S&&a.A.push({font:v,url:C,ieFix:ba,fontWeight:n,fontStyle:x,contentIdArray:p,isAjax:f,fFormat:g}))}}else if(C=ib(a,p,h,u,k,m,a.f.ck,v+(f?f:""),n,x,e?null:b,g,E,f,!1,A)){var ba="";a.m&&a.i&&(ba="_"+x.charAt(0)+n/100,a.o[v]=v+ba);(new V).ia(A)&&(g=kb(a));z=jb(a,v,"",z,n,x,v,C,g,p,!0,"",!1,!0,f,ba,!1);!a.m&&a.S&&a.A.push({font:v,url:C,ieFix:ba,fontWeight:n,fontStyle:x,contentIdArray:p,isAjax:f,fFormat:g})}}if(!0===t||f)f?$a(a,w,f):$a(a,w);""!=z&&(D(a.a,"head",r),r.styleSheet?
r.styleSheet.cssText=z:r.appendChild(document.createTextNode(z)))}
function ib(a,c,b,f,d,e,g,h,l,k,m,r,z,t,w,y){function n(m,n){var p=a.f.env;d=d.replace("http://","").replace("https:///","");e=e.replace("http://","").replace("https:///","");d="https://"+d+(z?"ot/":"");e="https://"+e;if(n.ia(m))if(q=e+"?",q+=g+"&",q+="fctypeId="+("15"==W(a,"fctypeArray")[kb(a)]?"3":W(a,"fctypeArray")[kb(a)])+"&fcId="+c.TTF,q+="&env="+p+"&projectId="+b,void 0!=m){var p=m.unicode,v=m.text,I=m.lang,u=m.ot;void 0!=p&&(q+="&ranges="+p);void 0!=v&&(q+="&content="+v.replace('"',"%22").replace("'",
"%27").replace("#","%23").replace("?","%3F").replace("&","%26"));void 0!=I&&(q+="&languages="+I);void 0!=u&&(q+="&ot="+u)}else q="";else f?(q=e+"?",q+=g+"&",q+="fctypeId="+("15"==W(a,"fctypeArray")[r]?"3":W(a,"fctypeArray")[r])+"&fcId="+c.TTF,11==r&&(q+="&origId="+x),void 0!==p&&""!=p&&(q+="&env="+p)):(""!==a.qa[r.toUpperCase()]?d+=a.qa[r.toUpperCase()]+"/":d+=a.qa.WOFF+"/",q=d+x+"."+r.toLowerCase()+"?"+g,a.i?E=k.charAt(0)+l/100:E="n4",p=h+"_"+E,-1<a.a.indexOf(a.O,p)&&(q=""),0>a.a.indexOf(a.O,p)&&
!w&&!z&&!t&&a.O.push(p)),""!=q&&(q+="&projectId="+b,null!=r&&"SVG"==r.toUpperCase()&&(q+="#"+x));return q}var x=c[r.toUpperCase()],q,u,v,p,E,A;U.UseHybrid&&(A=X(h),a.i?(E=k.charAt(0)+l/100,A=X(h,E)):E="n4",1==f&&lb(A)&&(f=!1));A=new V;if(A.ia(y))q=n(y,A);else if(f||U.EnableDSForAllFonts){if(m){m=fb(m,h,l,k);if(null==m)return q="";if(m){p=m.split("").sort().join("");m=h;a.w&&(m+="_"+k.charAt(0)+l/100);p=hb(a,p,m,t);t&&(a.w?m=m.substring(0,m.length-8)+"_"+k.charAt(0)+l/100:m=m.substring(0,m.length-
5)+"_n4",a.$[m]=p);p=mb(a,p).split("::");m=p[0];p=p[1].replace(":","");m&&(v=m.replace('"',"").replace("?","").replace(";","").replace("#","").replace("&","").replace("%","%25"));if(v&&0<v.length||p&&0<p.length)u="&content="+(v||"")+"BESb\uc5d0swyMm",""!=p&&(u+=p);q=n(y,A)+u}else return}}else n(y,A);return q}
mti.s.prototype.Y=function(a,c,b){if(!(null!=a&&1>a.length)){var f=this.f.projectId,d=this.f.fcURL,e=this.f.ck,g="";!this.m&&this.S&&0<this.A.length&&(g=eb(this,g));var h,l,k=this.c.oa,m=this.c.getName(),m=m.toLowerCase(),r="msie"==m&&8>=k?!0:!1,m=!1,z={TTF:"truetype",WOFF:"woff",SVG:"svg",MTX:"truetype",OTF:"opentype",WOFF2:"woff2"},k=[];a=b?a:this.h;for(var t=0,w="n4",y=0;y<this.f.pfL.length;y++){var n=this.f.pfL[y],x=!1,q=n.fontfamily;n.enableSubsetting&&this.pa++;if(b)x=!0;else for(var u=0;u<
a.length;u++)if(a[u].fontfamily==q&&(n.enableSubsetting||U.EnableDSForAllFonts)&&(this.w?a[u].fontWeight==n.fontWeight&&a[u].fontStyle==n.fontStyle&&(x=!0,h=n.fontWeight,l=n.fontStyle,w=l.charAt(0)+h/100,t=X(q,w)):(t=X(q),x=!0),x)){t=u;a.splice(t,1);break}x&&(t=X(q),n.enableSubsetting||U.EnableDSForAllFonts)&&((void 0!=n.fontWeight&&void 0!=n.fontStyle&&(h=n.fontWeight,l=n.fontStyle,w=l.charAt(0)+h/100,t=X(q,w)),k.push(t),contentIdArray=n.contentIds,enableOtf=n.enableOtf,lb(t)||b)?lb(t)&&b&&(this.h.push(new S(q,
w)),fFormat=this.X(contentIdArray),fontURL=ib(this,contentIdArray,f,!1,d,"",e,q,h,l,null,fFormat,enableOtf,!1,!1),""!=fontURL&&(n="",this.m&&this.i&&(n="_"+l.charAt(0)+h/100),this.ga.push(t),g=jb(this,q,"",g,h,l,q,fontURL,fFormat,contentIdArray,!0,"",!1,!0,!1,n,!1))):(m=!0,0>this.a.indexOf(this.ga,t)&&(fFormat=this.X(contentIdArray),fontURL=ib(this,contentIdArray,f,!1,d,"",e,q,h,l,null,fFormat,enableOtf,!1,!0),""!=fontURL&&(this.ga.push(t),r&&void 0!=l&&void 0!=h&&(q+="_"+l.charAt(0)+h/100),g+='@font-face{\nfont-family:"'+
t+'";',g+='\nsrc:url("'+fontURL+'")',null!=fFormat&&"EOT"==fFormat.toUpperCase()||"MTX"==fFormat.toUpperCase()||(q=z[fFormat.toUpperCase()],contentIdArray[fFormat.toUpperCase()]||(q=z.TTF),g+=" format('"+q+"')"),g+=";}\n"))))}""!=g&&(b=this.a.getElementById("mti_fontface_"+f),null==b&&(b=this.a.createElement("style",{type:"text/css",id:"mti_fontface_"+this.f.projectId}),""!=g&&D(this.a,"head",b)),b.styleSheet?""!=b.styleSheet.cssText?this.m?(b=this.a.getElementById("mti_fontface_"+(c?"hybridAjaxIE_":
"hybridIE_")+this.f.projectId),null==b&&(b=this.a.createElement("style",{type:"text/css",id:"mti_fontface_"+(c?"hybridAjaxIE_":"hybridIE_")+this.f.projectId}),""!=g&&D(this.a,"head",b)),b.styleSheet.cssText=g):b.styleSheet.cssText=g:b.styleSheet.cssText=g:(this.S&&(b=this.a.getElementById("mti_fontface_"+(c?"hybridAjaxIE_":"hybridIE_")+this.f.projectId),null==b&&(b=this.a.createElement("style",{type:"text/css",id:"mti_fontface_"+(c?"hybridAjaxIE_":"hybridIE_")+this.f.projectId}),""!=g&&D(this.a,"head",
b))),b.innerHTML+=g));if(m){c=[];for(g=0;g<k.length;g++)c.push(new S(k[g]));Ta(new Sa(this.c,this.a,new Ga(this.a,document.documentElement,{fontactive:function(a){if("_f"==a.substr(a.length-2)&&!lb(a)){var b=new Date;a=a.replace(/\s+/g,"%20");b.setDate(b.getDate()+1);document.cookie=a+"="+("1; expires="+b.toUTCString())}}}),6E5),c,{},{},!1)}}};
function eb(a,c){if(0<a.A.length)for(var b=0;b<a.A.length;b++){var f=a.A[b].font;c=jb(a,f,"",c,a.A[b].fontWeight,a.A[b].fontStyle,f,a.A[b].url,a.A[b].fFormat,a.A[b].contentIdArray,!0,"",!1,!0,a.A[b].isAjax,a.A[b].ieFix,!1)}return c};var U=window.MTIConfig||{eb:!1,Va:!1,Ya:!1};function V(a,c,b,f){this.Sa=a;this.a=c;this.Pa=b;this.U={};this.F=[];this.h=[];f?this.Ca=f:!1;this.Ja="img script noscript iframe object style param embed link meta head title br hr svg path".split(" ")}
V.prototype=function(){function a(a){var c=!1;void 0!=typeof a&&null!=a&&""!=a&&(void 0!=typeof a.lang&&null!=a.lang&&""!=a.lang?c=!0:void 0!=typeof a.unicode&&null!=a.unicode&&""!=a.unicode?c=!0:void 0!=typeof a.text&&null!=a.text&&""!=a.text?c=!0:void 0!=typeof a.ot&&null!=a.ot&&""!=a.ot&&(c=!0));return c}function c(a,f,d){if(void 0!==a&&null!==a&&""!==a&&a.tagName&&1===a.nodeType)for(0>d.a.indexOf(d.Ja,a.tagName.toLowerCase())&&(f?d.za(a,f):d.za(a)),a=a.firstChild;a;)c(a,f,d),a=a.nextSibling}return{za:function(b,
c){var d=this.Pa,e=this.a.getComputedStyle(b),g=e.fontFamily,h="",l=e.fontStyle,k=0,m=0,r="",g=(g||"").replace(/^\s|\s$/g,"").replace(/'|"/g,"").replace(/,\s*/g,"|");if(""!=g)for(var z=g.split("|"),t="",k=0;k<z.length;k++)for(m=0;m<d.length;m++){var w=d[m],t=w.fontfamily,y,n,x=w.enableSubsetting,q=w.enableOtf,u=w.contentIds,v=w.subsetOption,p=!1,E=t,A=new RegExp("^("+z[k]+")$","ig");if(void 0!=w.fontWeight&&void 0!=w.fontStyle)y=w.fontWeight,n=w.fontStyle,r=n.charAt(0)+y/100,h="normal"==e.fontWeight?
400:"bold"==e.fontWeight?700:e.fontWeight;else{var F="h1 h2 h3 h4 h5 h6 strong b".split(" ");1==b.nodeType&&(h=0<=this.a.indexOf(F,b.tagName.toLowerCase())?400:"normal"==e.fontWeight?400:"bold"==e.fontWeight?700:400)}if(void 0!=y||void 0!=n)E+="_"+r;var F=t.replace(/^\s|\s$/g,""),C=E.replace(/^\s|\s$/g,""),M=A.test(F),A=A.test(C);if(M||A)void 0!=y||void 0!=n?E==g?(p=new S(C),p.fontfamily=F,p.fontWeight=y,p.fontStyle=n,p.enableSubsetting=x,p.contentIds=u,p.enableOtf=q,p.subsetOption=v,this.h.push(p),
this.F.push(b),p=!0):h==y&&l==n&&(p=new S(F,r),p.fontfamily=F,p.fontWeight=y,p.fontStyle=n,p.enableSubsetting=x,p.contentIds=u,p.enableOtf=q,p.subsetOption=v,this.h.push(p),this.F.push(b),p=!0):(r="n4",p=new S(F),p.fontfamily=F,p.fontWeight=h/100,p.fontStyle=l.charAt(0),p.enableSubsetting=x,p.contentIds=u,p.enableOtf=q,p.subsetOption=v,this.h.push(p),this.F.push(b),p=!0),p&&(1==U.EnableCustomFOUTHandler&&H(b,c?"mti_font_element"+c:"mti_font_element"),x=b.getAttribute("style"),(x=null!=x?"string"==
typeof x?x:"cssText"in x?x.cssText:"":"")&&-1<this.a.indexOf(x,"font-weight")&&-1<this.a.indexOf(x,"font-style")?t+="_"+l.charAt(0)+h/100:t+=1<r.length?"_"+r:"",this.Ca||!w.enableSubsetting&&!U.EnableDSForAllFonts||a(v)||(w="",w=qa(this.a,b),this.U[t.replace(/^\s|\s$/g,"")]&&(w+=this.U[t.replace(/^\s|\s$/g,"")]),this.U[t.replace(/^\s|\s$/g,"")]=w))}},M:function(a,f){c(this.Sa,f,this);var d=!1,e;for(e in this.U)if(d=!0,this.Ca)break;else this.U[e]=xa(this.U[e]);return d?this.U:null},ba:function(){var a=
this.h,c=null==a?0:a.length,d={},e,g=[];for(e=0;e<c;e+=1)d[a[e].T+"||"+a[e].Z+"||"+a[e].W]=a[e];for(e in d)g.push(d[e]);return this.h=g},cb:function(){return this.F},ia:a}}();mti.s.prototype.X=function(a){var c=W(this,"ffArray"),b=this.K,f=this.version.j+this.version.J/10;"firefox"==this.K&&(b="mozilla");/ipad|ipod|iphone/.test(this.c.la.toLowerCase())&&(b="msafari");var c=c[b],b="",d;for(d in c)parseFloat(f)>=parseFloat(d)&&a[c[d].toUpperCase()]&&(b=c[d]);return b};function nb(){for(var a="",c=0;5>c;c++)a+="abcdefghijklmnopqrstuvwxyz".charAt(Math.floor(26*Math.random()));return a}
function ob(a,c){for(var b=0,f=0,d=!1,b=0;b<c.length;b++){d=!1;for(f=0;f<a.length;f++)c[b]==a[f]&&(d=!0);if(0==d&&f==a.length)return 0}return 1}mti.s.prototype.ua=function(a){if((a.ctrlKey||a.metaKey)&&116==a.keyCode){a.preventDefault();a=document.cookie.split(";");for(var c=1;c<=a.length;c++){var b=a[c-1].split("="),f=b[0].substr(b[0].length-2);"1"==b[1]&&"_f"==f&&(document.cookie=b[0]+"=;expires=Thu, 01 Jan 1970 00:00:00 GMT")}document.location.reload(!0)}};
function mb(a,c){var b=W(a,"specialChar"),f=b.length.toString().length;if(c&&"string"==typeof c){for(var d="",e=c.length,g=null,h="",l=[],k=0;k<e;k++)if(g=c.charAt(k),-1<a.a.indexOf(b,escape(g))){if(-1==a.a.indexOf(l,g)){l.push(g);g=a.a.indexOf(b,escape(g));if(g.toString().length<f)var m=Array(1+f).join("0"),g=(m+g).slice(-m.length);h+=g}}else-1==a.a.indexOf(d,g)&&(d+=g);return d+"::"+h}return""}
function fb(a,c,b,f){var d="";c=void 0!=b&&void 0!=f?c+("_"+f.charAt(0)+b/100):c+"_n4";a&&a[c]&&(d=a[c]);return 0<d.length?d:null}mti.s.prototype.ba=function(){return this.h};B=mti.s.prototype;B.load=function(a){a(this.h,this.Ia)};
function $a(a,c,b){var f=new Fa("-"),d=document.getElementById("mti_stylesheet_"+a.f.projectId);null==d&&(d=a.a.createElement("style",{type:"text/css",id:"mti_stylesheet_"+a.f.projectId}));var e="";if(1==U.EnableCustomFOUTHandler||1==U.UseHybrid){for(var g=a.f.pfL,e=e+(".mti-loading .mti_font_element"+(b?"_Aj":"")+"{"+a.ca+"}\n"),h=0;h<g.length;h++){var l=g[h].fontfamily,k="4",m="n";a.i&&(k=g[h].fontWeight/100,m=g[h].fontStyle.charAt(0),a.m&&(l=l+"_"+m+k,k="4",m="n"));b&&(l=l+b);l&&(e+="."+f.b("mti",
l,m+k,"loading")+" .mti_font_element"+(b?b:"")+"{"+a.ca+"}\n")}e+=".mti_hide_element{"+a.ca+"}"}for(h in a.f.selectorFontMap)if(f=a.f.selectorFontMap[h],l=f.familyName,a.i?(m=f.fontStyle,k=f.fontWeight):(m="normal",k="400"),c&&c[l]&&0<c[l].length&&(l=c[l].join("','")),b||(e=jb(a,l,h,e,k,m,"","","","",!1,f,!0)),1==U.EnableCustomFOUTHandler)for(m in e+="/*fout specific code:*/\n",k=h.split(","),m=void 0,k)e+=".mti-loading "+k[m]+"{"+a.ca+"}\n";""!=e&&D(a.a,"head",d);d.styleSheet?d.styleSheet.cssText+=
e:d.appendChild(document.createTextNode(e))}
function jb(a,c,b,f,d,e,g,h,l,k,m,r,z,t,w,y,n){1<a.a.indexOf(g,w)?w="":"";t?f+='@font-face{\nfont-family:"'+g+(w?w:"")+(y?y:"")+'";':"";a.m&&a.i&&!n&&(c+="_"+e.charAt(0)+d/100);t?"":f+=b+"{font-family:'"+c+"';";0==a.m&&a.i&&!n&&(f=f+("\n font-style:"+e+";")+("\n font-weight:"+d+";"));h?f+='\nsrc:url("'+h+'")':"";m?(c=f,null!=l&&"EOT"==l.toUpperCase()||"MTX"==l.toUpperCase()||(b=a.xa[l.toUpperCase()],k[l.toUpperCase()]||(b=a.xa.TTF),c+=" format('"+b+"')"),f=c):"";z?(l=f,null!=a.l&&(k=r.otf,r=r.vrnt,
k&&null!=k&&""!=k&&(l+=a.l.bb(k,r))),f=l):"";return f+=";}\n"}B.Fa=function(a){function c(){document.body?a():setTimeout(c,0)}c()};B.X=function(a){var c=W(this,"ffArray"),b=this.K,f=this.version.j+this.version.J/10;"firefox"==this.K&&(b="mozilla");/ipad|ipod|iphone/.test(this.c.la.toLowerCase())&&(b="msafari",f=this.c.Oa.j);var c=c[b],b="",d;for(d in c)parseFloat(f)>=parseFloat(d)&&a[c[d].toUpperCase()]&&(b=c[d]);""===b&&(b="ttf");return b};
function kb(a){var c=W(a,"ffArray"),b=a.K,f=a.version.j+a.version.J/10;"firefox"==a.K&&(b="mozilla");/ipad|ipod|iphone/.test(a.c.la.toLowerCase())&&(b="msafari");a=c[b];var c="",d;for(d in a)parseFloat(f)>=parseFloat(d)&&(c=a[d]);""===c&&(c="ttf");return c}B.ia=function(a){var c=!1;void 0!=typeof a&&null!=a&&""!=a&&(void 0!=typeof a.lang&&null!=a.lang&&""!=a.lang?c=!0:void 0!=typeof a.unicode&&null!=a.unicode&&""!=a.unicode?c=!0:void 0!=typeof a.text&&null!=a.text&&""!=a.text&&(c=!0));return c};
B.isArray=function(a){if(Array.isArray)return Array.isArray(a);Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)}};function X(a,c){void 0===c&&(c="n4");return a+"_"+c+"_f"}function pb(a,c){for(var b in c)if(a==c[b])return b;return!1};function qb(a,c,b){if(!window.MutationObserver||b){var f="string"==typeof c?document.getElementById(c):c;if(null!==f){b=!0;a.h=[];var d=a.f.projectId,e=a.f.fcURL,g=a.f.ck,h="",l,k;b=a.c.oa;var m="msie"==a.c.getName().toLowerCase()&&8>=b?!0:!1,r={TTF:"truetype",WOFF:"woff",SVG:"svg",MTX:"truetype",OTF:"opentype",WOFF2:"woff2"};b=!0;if(U.UseHybrid){b=!1;var z=a.a.getElementById("mti_fontface_"+d);null==z&&(z=a.a.createElement("style",{type:"text/css",id:"mti_fontface_"+d}),D(a.a,"head",z));var t=f.getAttribute("data-mtiFont"),
w=a.a.getComputedStyle(f);null==t&&(t=w.fontFamily.replace(/^\s|\s$/g,"").replace(/'|"/g,""));for(var y=[],n=0;n<a.f.pfL.length;n++)y.push(a.f.pfL[n].fontfamily);if(f.hasChildNodes&&0>a.a.indexOf(y,t))for(n=f.childNodes,u=0;u<n.length&&!(1==n[u].nodeType&&(t=a.a.B(n[u]).replace(/^\s|\s$/g,"").replace(/'|"/g,""),-1<a.a.indexOf(y,t)));u++);for(var x="normal"==w.fontWeight?"400":"bold"==w.fontWeight?"700":w.fontWeight,w=w.fontStyle,n=w.charAt(0)+x/100,q=t.split(","),u=0;u<q.length;u++){for(var v=X(q[u]),
p,E=!1,n=0;n<a.f.pfL.length;n++){p=a.f.pfL[n];var A=p.fontfamily;if(q[u]==A&&p.enableSubsetting)if(void 0!=p.fontWeight&&void 0!=p.fontStyle){if(l=p.fontWeight,k=p.fontStyle,w==p.fontStyle&&x==p.fontWeight){E=!0;n=k.charAt(0)+l/100;v=X(A,n);a.h.push(new S(A,n));break}}else{a.h.push(new S(A));E=!0;break}}if(lb(v)&&E)if(m&&-1<a.a.indexOf(a.O,t)){if(a.a.H(f,A,v,!1,!1),f.hasChildNodes)for(n=f.childNodes,u=0;u<n.length;u++)1==n[u].nodeType&&(t=a.a.B(n[u]).replace(/^\s|\s$/g,"").replace(/'|"/g,""),-1<a.a.indexOf(y,
t)&&a.a.H(n[u],A,v,!1,!1))}else{b=!1;contentIdArray=p.contentIds;enableOtf=p.enableOtf;fFormat=a.X(contentIdArray);p=A;m&&(void 0!=k&&void 0!=l?p+="_"+k.charAt(0)+l/100:p+="_n4");fontURL=ib(a,contentIdArray,d,!1,e,"",g,p,l,k,null,fFormat,enableOtf);""!=fontURL&&(h+='@font-face{\nfont-family:"'+p+'";',0==m&&void 0!=l&&void 0!=k&&(h+="\nfont-style:"+k+";",h+="\nfont-weight:"+l+";"),h+='\nsrc:url("'+fontURL+'")',null!=fFormat&&"EOT"==fFormat.toUpperCase()||"MTX"==fFormat.toUpperCase()||(l=r[fFormat.toUpperCase()],
contentIdArray[fFormat.toUpperCase()]||(l=r.TTF),h+=" format('"+l+"')"),h+=";}\n");if(z.styleSheet){if(z.styleSheet.cssText+=h,a.m&&(a.a.H(f,A,p,!1,!1),f.hasChildNodes))for(n=f.childNodes,u=0;u<n.length;u++)1==n[u].nodeType&&(t=a.a.B(n[u]).replace(/^\s|\s$/g,"").replace(/'|"/g,""),-1<a.a.indexOf(y,t)&&a.a.H(n[u],A,p,!1,!1))}else z.innerHTML+=h;a.$[p]=hb(a,"",p);if(!m&&(f.style.fontFamily=""+t,f.removeAttribute("data-mtiFont"),A="",f.hasChildNodes()))for(A=f.childNodes,h=0;h<A.length;h++)1==A[h].nodeType&&
A[h].getAttribute("data-mtiFont")&&(A[h].style.fontFamily=A[h].getAttribute("data-mtiFont"),A[h].removeAttribute("data-mtiFont"));if(null!=a.l){var F=new V(document.getElementById(c).parentElement,a.a,a.f.pfL);F.M({},C);mti.bind(a.l,a.l.ka,F.F)()}break}else b=!0}}if(b){var C=nb(),M=F=null,G=[],I=[],K=null!=f?f.parentElement:document.body;(function(){F=new V(K,a.a,a.f.pfL);M=F.M({},C);var b=[];if(void 0!=M)for(var d in M)d+=C,b.push(new S(e));a.P.mti_element_cache=F.F;ab(a,F.ba(),M,C,!0);b=F.F;null!=
a.l&&(d=[],d.push(f),mti.bind(a.l,a.l.ka,d)());for(d=0;d<b.length;d++)for(var e in a.o)-1<a.a.indexOf(a.a.B(b[d]),e)&&(b[d].getAttribute("id")==c||b[d]==c?a.a.H(b[d],e,a.o[e],m,a.w):wa(f,b[d])&&-1<a.a.indexOf(a.a.B(b[d]).replace(/'|"/g,""),e)&&a.a.H(b[d],e,a.o[e],m,a.w));d=null==a.o[e]?0:a.o[e].length;if(0<a.h.length)for(b=0;b<a.h.length;b++)e=a.h[b].getName()+C,d=null,a.w&&(d=R(a.h[b])),e=a.m&&null!=d?new S(e+"_"+d):null==d?new S(e):new S(e,d),G.push(e);else for(b=0;b<d;b++)a.w?G.push(new S(a.o[e][b],
"i6")):G.push(new S(a.o[e][b])),-1==a.a.indexOf(a.na,e)&&(a.na.push(e),a.w?I.push(new S(a.o[e][b],"i6")):I.push(new S(a.o[e][b])))})();1==U.RemoveMTIClass&&setTimeout(function(){rb(a,"mti_font_element"+C)},ga.va);b={};U.UseHybrid&&0<G.length&&(b.fontactive=function(){bb(a,a.Y,!0)},b.fontinactive=function(){bb(a,a.Y,!0)});1==U.EnableCustomFOUTHandler&&Ta(new Sa(a.c,a.a,new Ga(a.a,document.documentElement,b),ga.va),G,{},{},!1)}}}}mti.wa=function(a){this.Ma=a};
mti.wa.prototype={Ra:function(a,c){qb(this.Ma,a,c)}};
mti.s.prototype.sa=function(){var a=this,c="",b="img script noscript iframe object style param embed link meta head title br hr svg path".split(" ");if(window.MutationObserver){var f=new MutationObserver(function(b){b.forEach(function(b){if("characterData"==b.type)null!=b.target.parentNode&&(d=b.target.parentNode,"undefined"!==typeof d.getAttribute("isRender")&&"true"!==d.getAttribute("isRender")?(d.setAttribute("isRender","true"),null!=b.target.parentNode.id&&void 0!=typeof b.target.parentNode.id&&
"undefined"!==typeof document.getElementById(b.target.parentNode.id)&&null!=document.getElementById(b.target.parentNode.id)&&(c=document.getElementById(b.target.parentNode.id).getAttribute("data-mti-otf")),void 0!=typeof c&&"mti-otf"!=c&&Y(a,b.target.parentNode)):setTimeout(function(){d.removeAttribute("isRender")},0));else if("attributes"==b.type)if("style"==b.attributeName){var d=b.target;""==d.style.fontFamily&&""==d.style.fontWeight&&""==d.style.fontStyle||"BESb\uc5d0swy"==d.innerHTML||"BESbswy"==
d.innerHTML||("undefined"!==typeof d.getAttribute("isRender")&&"true"!==d.getAttribute("isRender")?(d.setAttribute("isRender","true"),null!=d.id&&""!=d.id&&void 0!=typeof d.id?"undefined"!==typeof document.getElementById(d.id)&&null!=document.getElementById(d.id)&&(c=document.getElementById(d.id).getAttribute("data-mti-otf")):null!=d&&""!=d&&void 0!=typeof d&&(c=d.getAttribute("data-mti-otf")),d=null!=d.id?d.id:d,"mti-otf"!=c&&""!=d&&Y(a,d)):setTimeout(function(){d.removeAttribute("isRender")},0))}else"class"==
b.attributeName&&sb(tb(b.target.classList))?Y(a,b.target):"id"==b.attributeName&&-1<b.target.id.indexOf("mtiSelector")&&Y(a,b.target);else if("childList"==b.type&&0<b.addedNodes.length)for(var f=0;f<b.addedNodes.length;f++)if(d=b.addedNodes[f],3==d.nodeType&&(d=d.parentNode),"undefined"!==typeof d&&null!=d&&3!=d.nodeType){var l=d.tagName;"HTML"!=l&&"HEAD"!=l&&"TITLE"!=l&&"STYLE"!=l&&"LINK"!=l&&"META"!=l&&"BASE"!=l&&"IMG"!=l&&"HR"!=l&&"BR"!=l&&"BESb\uc5d0swy"!=d.innerHTML&&"BESbswy"!=d.innerHTML&&
"undefined"!==typeof d.className&&"function"===typeof d.className.indexOf&&-1==d.className.indexOf("firebugLayoutBox")&&(null!=d.id&&""!=d.id&&void 0!=typeof d.id?null!=document.getElementById(d.id)&&(c=document.getElementById(d.id).getAttribute("data-mti-otf")):null!=d&&""!=d&&void 0!=typeof d&&(c=d.getAttribute("data-mti-otf")),d="undefined"!==typeof d.id&&null!=d.id&&""!=d.id?d.id:d,"mti-otf"!=c&&""!=d&&Y(a,d))}});ub(a,!0)});document.body&&f.observe(document.body,{childList:!0,characterData:!0,
subtree:!0,attributes:!0,attributeOldValue:!0,attributeFilter:["style","class","id"]})}else f=function(a,b){var c=document;c.addEventListener?c.addEventListener(a,b,!1):c.attachEvent("on"+a,b)},f("DOMNodeInserted",function(d){d=d.target;if(1>d.childNodes.length||""==d.innerHTML)return!1;void 0!=typeof d&&null!=d&&3==d.nodeType&&(d=void 0!==d.parentElement?d.parentElement:d.parentNode);if(0<a.a.indexOf(b,d.nodeName.toLowerCase()))return!1;if(void 0!=typeof d&&null!=d&&1==d.nodeType){var e=d.tagName;
"HTML"!=e&&"HEAD"!=e&&"TITLE"!=e&&"STYLE"!=e&&"LINK"!=e&&"META"!=e&&"BASE"!=e&&"IMG"!=e&&"HR"!=e&&"BR"!=e&&"BESb\uc5d0swy"!=d.innerHTML&&"BESbswy"!=d.innerHTML&&(void 0!=typeof d.id&&null!=d.id&&""!=d.id?"undefined"!==typeof document.getElementById(d.id)&&null!=document.getElementById(d.id)&&(c=document.getElementById(d.id).getAttribute("data-mti-otf")):void 0!=typeof d.getAttribute&&void 0!=typeof d&&null!=d&&""!=d&&(c=d.getAttribute("data-mti-otf")),"mti-otf"!=c&&""!=d&&(Y(a,d),ub(a,!1)))}}),f("DOMAttrModified",
function(b){if("style"==b.attrName){var e=b.target;"BESb\uc5d0swy"!=e.innerHTML&&"BESbswy"!=e.innerHTML&&("undefined"!==typeof e.getAttribute("isRender")&&"true"!==e.getAttribute("isRender")?(e.setAttribute("isRender","true"),void 0!=typeof e.id&&null!=e.id&&""!=e.id?void 0!=typeof document.getElementById(e.id)&&null!=document.getElementById(e.id)&&(c=document.getElementById(e.id).getAttribute("data-mti-otf")):void 0!=typeof e.getAttribute("data-mti-otf")&&null!=e&&""!=e&&(c=e.getAttribute("data-mti-otf")),
"mti-otf"!=c&&""!=e&&(Y(a,e),ub(a,!1))):setTimeout(function(){e.removeAttribute("isRender")},0))}else"class"==b.attrName&&sb(tb(b.target.className))?(Y(a,b.target),ub(a,!1)):"id"==b.attrName&&-1<b.target.id.indexOf("mtiSelector")&&(Y(a,b.target),ub(a,!1))}),f("DOMCharacterDataModified",function(b){b=b.target;void 0!=typeof b&&null!=b&&3==b.nodeType&&(b=b.parentElement);if(void 0!=typeof b&&null!=b&&1==b.nodeType){var e=b.tagName;"HTML"!=e&&"HEAD"!=e&&"TITLE"!=e&&"STYLE"!=e&&"LINK"!=e&&"META"!=e&&
"BASE"!=e&&"IMG"!=e&&"HR"!=e&&"BR"!=e&&"BESb\uc5d0swy"!=b.innerHTML&&"BESbswy"!=b.innerHTML&&(void 0!=typeof b.id&&null!=b.id&&""!=b.id?null!=document.getElementById(b.id)&&(c=document.getElementById(b.id).getAttribute("data-mti-otf")):void 0!=typeof b&&null!=b&&""!=b&&(c=b.getAttribute("data-mti-otf")),"mti-otf"!=c&&""!=b&&(Y(a,b),ub(a,!1)))}})};
function Y(a,c){if(void 0!=typeof c&&null!=c){var b=!1,f,d,e="";"string"==typeof c?(f=document.getElementById(c),null!=f&&(d=f.parentNode),null!=d&&(e=f.getAttribute("id")),-1==a.a.indexOf(a.G,c)&&-1==a.a.indexOf(a.G,e)&&(a.G.push(c),b=!0)):-1==a.a.indexOf(a.G,c)&&-1==a.a.indexOf(a.G,c.parentElement)&&(a.G.push(c),b=!0);b&&1==U.EnableCustomFOUTHandler&&(c="string"==typeof c?document.getElementById(c):c,void 0!=typeof c&&null!=c&&1==c.nodeType&&vb(a,c).v&&wb(a,c))}}mti.s.prototype.ta=null;
function ub(a,c){var b=50;c||(b=0);a.f.enableOtf&&(b=0);null!=a.ta&&clearTimeout(a.ta);a.ta=setTimeout(function(){if(-1<a.G.length){var b="",c=a.G.length;if(!(1>c)){for(var e=0;e<c;e++){var g="string"==typeof a.G[e]?document.getElementById(a.G[e]):a.G[e];if(void 0!=typeof g&&null!=g){var b=qa(a.a,g),h=new V(g,a.a,a.f.pfL),l=h.M(g),h=h.F,k=vb(a,g);k.v?""!=b?xb(a,a.G[e],b,k,l,h):(b="_n4",a.i&&(b=k.fontStyle.charAt(0)+k.fontWeight/100),null!=l&&(b=l[k.R+b],""!=b&&xb(a,a.G[e],b,k,l,h))):!k.v&&null!=g&&
g.hasChildNodes&&(k=yb(a,g),b=qa(a.a,k.node),h=new V(k.node,a.a,a.f.pfL),l=h.M(k.node),h=h.F,k.v&&xb(a,k.node,b,k,l,h))}}a.G=[]}}},b)}
function vb(a,c){if(1!=c.nodeType)return{v:!1};var b=a.a.getComputedStyle(c),f="test",d="normal",e="100";if(void 0!=typeof b&&null!=b)if(f=b.fontFamily,d=b.fontStyle,e="normal"==b.fontWeight?"400":"bold"==b.fontWeight?"700":b.fontWeight,b=null!=f?f.split(","):"",b instanceof Array)for(f=0;f<b.length;f++)for(var g=0;g<a.f.pfL.length;g++){var h=a.f.pfL[g],l=h.fontfamily,k=h.enableSubsetting,m=h.fontStyle,r=h.fontWeight,h=h.enableOtf;if(l==J(b[f])&&(k||h))if(a.w){if(m==d&&r==e)return{v:!0,R:l,fontWeight:e,
fontStyle:d}}else return{v:!0,R:l}}else for(f=0;f<a.f.pfL.length;f++)if(h=a.f.pfL[f],l=h.fontfamily,k=h.enableSubsetting,m=h.fontStyle,r=h.fontWeight,h=h.enableOtf,k||h)if(a.w){if(m==d&&r==e)return{v:!0,R:l,fontWeight:e,fontStyle:d}}else if(l==J(b))return{v:!0,R:l};return{v:!1}}function yb(a,c){var b={v:!1,R:"testFont"};if(1==c.nodeType&&(b=vb(a,c),b.v))return b.node=c,b;for(var f=c.childNodes,d=f.length,e=0;e<d;e++){var g=f[e];if(1==g.nodeType&&(b=yb(a,g),b.v))break}return b}
function zb(a,c,b){var f="string"==typeof c?document.getElementById(c):c;if(null!==f){var d=!0,e=[];a.h=[];var g=a.f.projectId,h=a.f.fcURL,l=a.f.ck,k="",m,r,d=!0;if(U.UseHybrid){var d=!1,z=a.a.getElementById("mti_fontface_"+g);null==z&&(z=a.a.createElement("style",{type:"text/css",id:"mti_fontface_"+g}),D(a.a,"head",z));var t=f.getAttribute("data-mtiFont"),w=a.a.getComputedStyle(f);null==t&&(t=w.fontFamily.replace(/^\s|\s$/g,"").replace(/'|"/g,""));for(var y=[],n=0;n<a.f.pfL.length;n++)y.push(a.f.pfL[n].fontfamily);
if(f.hasChildNodes&&0>a.a.indexOf(y,t))for(n=f.childNodes,q=0;q<n.length&&!(1==n[q].nodeType&&(t=a.a.B(n[q]).replace(/^\s|\s$/g,"").replace(/'|"/g,""),-1<a.a.indexOf(y,t)));q++);for(var y="normal"==w.fontWeight?"400":"bold"==w.fontWeight?"700":w.fontWeight,w=w.fontStyle,x=w.charAt(0)+y/100,t=t.split(","),q=0;q<t.length;q++){for(var u,n=0;n<a.f.pfL.length;n++){u=a.f.pfL[n];var v=u.fontfamily,p=X(v);if(t[q]==v&&u.enableSubsetting)if(a.i){if(m=u.fontWeight,r=u.fontStyle,w==u.fontStyle&&y==u.fontWeight){x=
r.charAt(0)+m/100;p=X(v,x);a.h.push(new S(v,x));e.push(new S(v,x));break}}else{x="n4";a.h.push(new S(v));e.push(new S(v));break}}lb(p)&&(d=!1,-1==a.a.indexOf(a.O,v+"_"+x)&&(contentIdArray=u.contentIds,enableOtf=u.enableOtf,fFormat=a.X(contentIdArray),fontURL=ib(a,contentIdArray,g,!1,h,"",l,v,m,r,null,fFormat,enableOtf),""!=fontURL&&(k+='@font-face{\nfont-family:"'+v+'";',a.i&&(k+="\nfont-style:"+r+";",k+="\nfont-weight:"+m+";"),k+='\nsrc:url("'+fontURL+'")',k+=";}\n",a.$[v+"_"+x]=hb(a,"",v+"_"+x))));
if(""!=k){z.styleSheet?z.styleSheet.cssText+=k:z.innerHTML+=k;f.removeAttribute("data-mtiFont");n="";if(f.hasChildNodes())for(var n=f.childNodes,E=0;E<n.length;E++)1==n[E].nodeType&&n[E].getAttribute("data-mtiFont")&&(n[E].style.fontFamily=n[E].getAttribute("data-mtiFont"),n[E].removeAttribute("data-mtiFont"));if(null!=a.l){var A=new V(null!=f&&f!=document.body?f.parentElement:document.body,a.a,a.f.pfL);A.M({},F);mti.bind(a.l,a.l.ka,A.F)()}}else d=!0}}if(d){var F=nb(),C=A=null,M=[],G=null!=f&&f!=
document.body?f.parentElement:document.body;if(null==f.parentElement||b)G=document.body;(function(){A=new V(G,a.a,a.f.pfL);C=A.M({},F);if(void 0!=C)for(var b in C)26<b.length&&(a.C[b]||(a.C[b]="mtiFont"+a.Da++)),void 0!==a.C[b]&&""!==a.C[b]&&(b=a.C[b]),b+=F;a.P.mti_element_cache=A.F;ab(a,A.ba(),C,F,!0);b=A.F;null!=a.l&&mti.bind(a.l,a.l.ka,b)();for(var d,h,g=0;g<b.length;g++){var l=a.a.getComputedStyle(b[g]),k;for(k in a.o)a.i&&(d=k.slice(-2),k=k.slice(0,-3),h=l.fontWeight,h=l.fontStyle.charAt(0)+
h/100),-1<a.a.indexOf(a.a.B(b[g]),k)&&(a.i?d==h:1)&&(b[g].getAttribute("id")==c||b[g]==c?a.a.H(b[g],k,a.o[k+(a.i?"_"+d:"")],!1,a.w):wa(f,b[g])&&-1<a.a.indexOf(a.a.B(b[g]).replace(/'|"/g,""),k)&&(a.i?d==h:1)&&a.a.H(b[g],k,a.o[k+(a.i?"_"+d:"")],!1,a.w))}b=null==a.o[k]?0:a.o[k].length;if(0<a.h.length)for(d=0;d<a.h.length;d++)a.h[d].enableSubsetting&&(k="n4",a.i&&(k=R(a.h[d])),b=(void 0!==a.C[a.h[d].getName()+"_"+k]?a.C[a.h[d].getName()+"_"+k]:a.h[d].getName())+F,k=null!=k?new S(b,k):new S(b),e.push(k));
else for(d=0;d<b;d++)a.i?e.push(new S(a.o[k][d],"i6")):e.push(new S(a.o[k][d])),-1==a.a.indexOf(a.na,k)&&(a.na.push(k),a.i?M.push(new S(a.o[k][d],"i6")):M.push(new S(a.o[k][d])))})();1==U.RemoveMTIClass&&setTimeout(function(){rb(a,"mti_font_element"+F)},5E3)}b={};0<e.length&&(b.fontactive=function(b,c,d){U.UseHybrid&&bb(a,a.Y,!0);for(var e=0;e<window.MonoTypeWebFonts._fontActiveEventList.length;e++)d=b.slice(0,-5),window.MonoTypeWebFonts._fontActiveEventList[e].call(window.MonoTypeWebFonts,b,c,d)},
b.inactive=function(a,b,c){for(var d=0;d<window.MonoTypeWebFonts._inActiveEventList.length;d++)c=a.slice(0,-5),window.MonoTypeWebFonts._inActiveEventList[d].call(window.MonoTypeWebFonts,a,b,c)},b.fontloading=function(a,b,c){for(var d=0;d<window.MonoTypeWebFonts._fontLoadingEventList.length;d++)c=a.slice(0,-5),window.MonoTypeWebFonts._fontLoadingEventList[d].call(window.MonoTypeWebFonts,a,b,c)},b.active=function(){for(var a=0;a<window.MonoTypeWebFonts._activeEventList.length;a++)window.MonoTypeWebFonts._activeEventList[a].call(window.MonoTypeWebFonts)});
1==U.EnableCustomFOUTHandler&&Ta(new Sa(a.c,a.a,new Ga(a.a,document.documentElement,b),5E3),e,{},{},!1)}}
function xb(a,c,b,f,d,e){var g=c;"string"==typeof c&&(g=document.getElementById(g));f=c==f.node?!0:!1;var h="",h="";if(null!=d)for(var l in d){if(""!=d[l]){var k=l.slice(0,-3);fntVariant=l.slice(-2);var m=k;void 0!==a.C[l]&&(k=a.C[l]);b+=void 0!==d[k+"_"+fntVariant]?d[k+"_"+fntVariant]:"";h=xa(b);h=h.split("").sort().join("");l=25<k.length?k.substring(0,20)+fntVariant:l;var h=hb(a,h,k+"abcde"+(a.i?"_"+fntVariant:""),!0),r=a.$[k+"_"+fntVariant];if(-1==a.a.indexOf(a.O,l))if(U.UseHybrid)if(lb(X(m,fntVariant)))zb(a,
c,f);else if(h!=r){for(var z in e)h=vb(a,e[z]),h.v&&(b=qa(a.a,e[z]),""!=b&&(m=hb(a,"",k+"abcde"+(a.i?"_"+fntVariant:""),!0),h=xa(b).split("").sort().join(""),ob(xa(m),h)||zb(a,e[z],f)));zb(a,c,f)}else null!=a.l&&Ab(a,c),-1<a.ga.indexOf(l+"_f")&&-1==a.O.indexOf(l)&&(textCollector=new V(g,a.a,a.f.pfL),d=textCollector.M({}),ab(a,textCollector.ba(),d));else if(h!=r)zb(a,c,f);else{var k=a.a.B(g),r=g.getAttribute("data-mtiFont"),t=!0,h=vb(a,g);h.v&&a.i&&(t=a.a.getComputedStyle(g),k=t.fontFamily,fntStyle=
t.fontStyle,fntWeight=t.fontWeight,t=fntStyle==h.fontStyle&&fntWeight==h.fontWeight?!0:!1);if(-1==k.indexOf(a.V[l])&&-1<k.indexOf(r)&&0==a.V[l].indexOf(r)&&t)a.a.H(g,m,a.V[l],!1,!1);else for(z in e)h=vb(a,e[z]),h.v&&h.R===m&&(k=a.a.B(e[z]),t=!0,r="n4",a.i&&(t=a.a.getComputedStyle(e[z]),k=t.fontFamily,fntStyle=t.fontStyle,fntWeight=t.fontWeight,r=h.fontStyle.charAt(0)+h.fontWeight/100,t=fntStyle==h.fontStyle&&fntWeight==h.fontWeight?!0:!1),void 0!==a.V[m+"_"+r]&&-1==k.indexOf(a.V[m+"_"+r])&&t&&a.a.H(e[z],
m,a.V[m+"_"+r],!1,!1));null!=a.l&&Ab(a,c)}else null!=a.l&&Ab(a,c)}}else null!=a.l&&Ab(a,c);1==U.EnableCustomFOUTHandler&&rb(a,"mti_hide_element")}function Ab(a,c){var b="string"==typeof c?document.getElementById(c):c,f=new V(null!=b?c.parentElement:document.body,a.a,a.f.pfL);f.M({});f=f.F;0==f.length&&f.push(b);mti.bind(a.l,a.l.ka,f)()}function tb(a){for(var c=[],b=a.length>>>0;b--;)c[b]=a[b];return c}
function wb(a,c){var b="img script noscript iframe object style param embed link meta head title br hr svg path".split(" "),f=vb(a,c),d,e;f.v&&(d=f.R,e="n4",a.i&&(e=f.fontStyle.charAt(0)+f.fontWeight/100));if(void 0!==c&&null!==c&&""!==c&&c.tagName&&1===c.nodeType&&0>a.a.indexOf(b,c.tagName.toLowerCase())){var g=qa(a.a,c),b=!1;""!=g.replace(/\s/g,"")&&f.v&&(500>g.length?(f=g.split("").sort().join(""),hb(a,f,d+"abcde"+(a.i?"_"+e:""),!0)!=a.$[d+"_"+e]&&(b=!0)):b=!0,b&&H(c,"mti_hide_element"));for(c=
c.firstChild;c;)wb(a,c),c=c.nextSibling}}function sb(a){var c,b=a.length,f=!1;for(c=0;c<b;c++)if(-1<a[c].indexOf("mtiSelector")){f=!0;break}return f};function lb(a){a=a.replace(/\s+/g,"%20");a=document.cookie.split(a+"=");var c=null;2==a.length&&(c=a.pop().split(";").shift());return 1==c?!0:!1}
function hb(a,c,b,f){var d="";f&&(a.w?(d=b.substring(b.length-3,b.length),b=b.substring(0,b.length-8)):b=b.substring(0,b.length-5));pb(b,a.C)&&(b=pb(b,a.C).slice(0,-3));b+=d;if("undefined"!==typeof Storage){a:{var e;try{e=window.localStorage.getItem(b)}catch(g){console&&console.log("MTI_webfont_service::localStorage.getItem error::"+g.message);a=!1;break a}a=null==e?!1:e.length>c.length?ob(e,c)?e:!1:!1}if(0==a&&c){a=c;try{null!=window.localStorage.getItem(b)&&(a+=window.localStorage.getItem(b)),a=
xa(a).split("").sort().join(""),window.localStorage.setItem(b,a)}catch(h){console&&console.log("MTI_webfont_service::localStorage.setItem error::"+h.message)}}else if(0<a.length)return a}return c};function rb(a,c){for(var b=sa(a.a,c),f=new RegExp(c,"ig");0<b.length;){for(var d=0;d<b.length;d++)1!=b[d].className.split(" ").length||a.ra?b[d].className=b[d].className.replace(f," ").replace(/^\s+|\s+$/g,""):b[d].removeAttribute("class");b=sa(a.a,c)}}
mti.s.prototype.H=function(a,c,b,f,d){var e=this.B(a).split(","),g=[];if(b instanceof Array){for(var h in b)b.hasOwnProperty(h)&&g.push(b[h]);f&&(d&&(b=pa(this,a),f=oa(this,a),g.push(c+"_"+b.charAt(0)+f/100)),a.style.fontWeight="",a.style.fontStyle="");for(h in e)e.hasOwnProperty(h)&&g.push(e[h]);g=va(g);a.style.fontFamily=g;a.setAttribute("data-mtiFont",c)}};
function cb(a,c){if(!0===mti.s.b)c();else{var b=a.a.D;if("MSIE"==a.c.getName()){var f=!1,d=function(){f||(f=!0,c(),mti.s.b=!0)};(function(){try{if("msie"==a.K&&11<=a.version.j?b.documentElement.scrollLeft:b.documentElement.doScroll("left"),"complete"!=b.readyState){setTimeout(arguments.callee,50);return}}catch(c){setTimeout(arguments.callee,50);return}d()})();b.onreadystatechange=function(){"complete"==b.readyState&&(b.onreadystatechange=null,d())}}else"AppleWebKit"==a.c.Ha&&525>a.c.Ga.j?function(){-1<
["loaded","complete"].indexOf(b.readyState)?(c(),mti.s.b=!0):setTimeout(arguments.callee,50)}():b.addEventListener?"loading"==b.readyState?b.addEventListener("DOMContentLoaded",function(){c();mti.s.b=!0},!1):window.addEventListener("load",function(){c();mti.s.b=!0},!1):window.onload=function(){c();mti.s.b=!0}}}
function bb(a,c,b){"complete"==document.readyState?setTimeout(function(){c.apply(a,[a.h,b,!1])},500):document.addEventListener("readystatechange",function(){"complete"==document.readyState&&setTimeout(function(){c.apply(a,[a.h,b,!1])},500)});document.addEventListener?document.addEventListener("keydown",function(b){a.ua.apply(a,[b])}):window.attachEvent?window.attachEvent("onkeydown",function(b){a.ua.apply(a,[b])}):document.addEventListener("keydown",function(b){a.ua.apply(a,[b])})};
})(this,document);